"""
B2B service agreements with in-app e-signature.

Flow:
  1. sevs opens /agreements (passcode-gated, same TRIXIE_ASSISTANT_PASSCODE as
     the VA tool suite), enters the client's details -> agreement is created
     and the signing link is emailed to the client (and returned for texting).
  2. Client opens /sign/<token> on any device: reads the full agreement,
     types their name/title, optionally draws a signature, checks the ESIGN
     consent box, and signs.
  3. Backend stamps the executed copy (signer, timestamp, IP, user agent),
     stores an immutable HTML snapshot + SHA-256, and emails both parties.
     Re-opening the link shows the executed copy.

Serving shape: the app-wide CSP is `default-src 'none'` except for the
internal-tool branch (style-src/script-src/img-src 'self'), so these pages
load their CSS/JS/logo from same-origin routes below — NO inline styles or
scripts (they would be silently blocked by the browser). server.py's CSP
middleware includes /agreements and /sign/ in the tool branch.

Legal shape (ESIGN/UETA click-to-sign): explicit consent language, signer
identity, audit trail, retained records for both parties. Not a substitute
for attorney review of the underlying terms.
"""
import base64
import hashlib
import hmac
import logging
import os
import secrets

from flask import Blueprint, Response, jsonify, request

from extensions import limiter
from models import db, Agreement, utcnow

logger = logging.getLogger(__name__)

agreements_bp = Blueprint("agreements", __name__)

SEVS_NOTIFY_EMAIL = "se7nz7@gmail.com"

# 140px U-truck logo (brand asset), served same-origin at /agreements/logo.png
# because the CSP tool branch only allows img-src 'self' data:.
_LOGO_B64 = "iVBORw0KGgoAAAANSUhEUgAAAIsAAACMCAYAAABMHFpHAAAAAXNSR0IArs4c6QAAAERlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAA6ABAAMAAAABAAEAAKACAAQAAAABAAAAi6ADAAQAAAABAAAAjAAAAAA49P1sAABAAElEQVR4AeW9CdhmVXUmes43/VPNcxWTCIJCq4iatEaNxDEQ9YqCehs12LnENkG9tra59vPclE/ftImx206cojdRE3GiJEZQSaIIGh9NG8QRBUVlqCpqnv75G+/7vmutffb3/X8hajqBurvqO3vvtde011p7OONfzrzhtectHjlwVrfX6jUaZa1eG/S7vaI/WJzt1LuDfrs1Vm+259oLR+b7jQm0d4ter9msFcViUQwmy6LT6Q8WOr1iDET1sUZz5Zqxfn1Qb9WLorfYK+rN5qDo9wegKWuLi53a/LHFbhdM5rtl0SiKxqBVdotuMYDcRjFWtCeazebKqVbZL2q9WlFvTIwfm59a9/2T3/rWncUJlAaDQbn/Na88sz/TeUSz1m0Vg2bZG8AmgNcHtX5R9oHS7RcFyrVaWccPZiyLbreEVQv+hxu6vW6/bPTKWm+sX6v3G6Bu9Ba7i/3WYNDv0V71ejEGwkW0lI1GrY683R3UG6Af1MpBvd3uDUAp3EGHrivLVqve64NnrV+OlbVytlHvNMvm1xoLt93+rO7uPf8ezuq0wbuEcoMCjFGG6swHHZTh13IAZTtqqw0AQr+ACQriMKuhq93+ThQHxaI3dGuoIJVlOZBCRQ3/YALw6YkfW5GgeA845NwtYB/k/UG/2ZmYuK2xYtWfAOOECpYd6PGvfPe2xxXTM7/T6/fX1+plF/6FCdF/hEoN5pahUKd9aTvYG87pEwXmqvcWUWKlB1sOGF7AQNwgHIrCfEnHFMUcfsSjX7vMEYIY6oCVRU/hCWklyRCLwAIrOh4FBNagX6/Vx440Nq97Q6OHiQJi2iXjQIkiqal8DLI8WRBRvUhsB2tDhziPDapvpFAMGGBm/BAC+GfKQx82MJAAZA2t1BS4lEB9EaCIHaEBcmKlNkdDrYTtB224Cn6AyzBUMW5oghLOUofDcqzAOGglmmJJiAwiksDxjAQzKosk8GRlWNiBRGWCXITfoKizBT+YH3ECxQbwJBox4Q9qtV6ng+hocC4yMjtCP9SNI2hBiK44AsuBHDA2KQopSbTqkCiIk+NHOXIiaQQhF7+MKWefVMW0diImrARDCQsAlwNzCJ2XWa+yLf2BQUnnDFEDGxQG5JE148ACcQVgmXjuW/guJjD3n2GZ7xMF1jwEC+KQUYmhDX5Qo4aAstFNgOYmsLfEoECwgX0wkRKUK4QUNFZjhAt3lC6oEXocHqg6PegY4RUZIx2tnDtPwITthDmKBqEJNKsu11F4AnZhCw8cSGYxQuilcAgcISxAiRBloo0kUQWMeI6Pua3gfqVmqxkxxKXRqw1qTa5SjABMRpBEXCjD5SRXx7hy1gECMEx5VqgVMQ1bRyJYouOpP7ECysb4sYliAaBc/pjET2Xoo2XsxIuWS9jRepPGoxU43SPvc9+qZPaULWgZh7ptUEsQ2gmUdJ4hsYiEWYB800gmF2IwN8SUqyo4DghYjV/S48dVUfsGIDW6PfMmWcht8JsHE/iyE3QzcJCAoVa1U7ASw9rFMyCMTRUgbApcz8mPvFKT71PUHLjk7VujE3QVgl04GLhhRafNiHSwvEkzCCTTWo0AwhgYHLhYEpDM+MQgG6Gz7EkBUu0eUjvx6APRgVB8UIG7EwupIgSMaOiJEzKxAymRqh8pGGHaoVMJESHStPNh4OLEBbt3aAs00PEHJArldBJqBHfXnRylDA/EBWE0pY4kCJAQ2rSJaBLiCVDA2RBmkTbP+miCyoayHRrd5uy4bORBYWUONlgyli3aJ7OR2dhmFZbpD+XJv2ZAwyN/JsORO9wBDqecGk7VSuxZwnm5W6MM/0ttHqrZgIwDQ2KoBBAZlOqEBJsSyfGGyKMapGjWyEhTh4Y4G/qJeOQytLcXi4730O2hwabhBotomYbJYN8hX8mTdLDbmXVUBHZ2kdG2LMvmApovjdZ5CMOw3EGBzz2JUqOPuQUl/cBSJEkgHccKAkr7E0ckJU6wob8poTMXUjLwgM+6dSxbahhQSAqKpBghlkY7EnAQ4Nz5BE1xJsp9mTskbJoHjHoPmyW/0JZhQwBZdONytg505bI3GtkOb2hAGobTOF/6k3AdyJIF58W4aCAWeOYKMKH6OW5FhRI4WFBUjWRqgQA68tJPuMFKlTiYIqwRl3z4qwKELVkKQTKga5w1n2hFdHeok8kuHKSypwdH2DZyGILtYS6zS2Vr1omaJ/ObuKotfEcewUe5E2ruQ+h0Bx3sWRhRPG/2NRHsgyYRExYRXwnOAiQJIq3BjYnVWc5/gVPx8pIRodnrHHE8SzhBU9128EP+tkCxAWXdtjLhZoilNg1HxaySmysCL0yat9EPw3WXmMHlAlyMw9VSxAoTOIEs8QuF2VRxyxgDs4ITy1JiEID7yJcGH3lytrKoFyk3z0wn6jqECy00vfroB9ke443A+EV7OD7ZiAhwBH3BSPJoErr8EzBuD/jzRD6smL2H5RMl+DOnA4iLa3K85YNqYuOIXg/luFZFWWspCPNEpq53tpcx5SrBFUXwYlvsharWkRK6iSubZH/CJd0LQ0yEG82JPsdnPgnbwseZHUAFu4Ttk01pK2HhgNUi7J8bjzYPRmiHF4IiNLGQyPYxGLY13OhFrIBQkUYGEZ0hhDqHIkTMA4cKEM/arZN5d9iuZEyiZuql2nEK3htYkl322nFwH8RgTvMwT9U/72vESrI98QSEvWEUs7t1nMSqxzaSYIZRxpekFS8fpCA0lnZCQh4kjaQ2VgiFzBp2LjjVx60kKeANymzvkaiDMdoggrUU1VYnv4jMyE3BgJuyOA4PEXEcOoB70IycXA6hnQgVOETGpNfKEo8jjKTkQLSbL2LvYogxRVhb5mzxA0+g8VcFigmM+Yz0oiWSJ+NldDzvxa3uGu6MY26JCztADAe5VsaFAeDU5uQqEMQ7E8J6KKc2P4yi5PWcZ3SIecJJ0nOOJ0a53zVbhkWj/6O9y5dqukL4YaDInSgFF+osV7QVouSAEf3NctTJgvyJCRj+WfDhtpCIeTVf0SymPgUqNnCo2DsHGwTRDIQskoVisw2KiTZ4SCE2OI+Ag4JaJfwU8Y4gYSNyxOZBfuAV3FqTV+01Mqyb7pwlXWMr7ZSlVImCcIhHt1SzvprNfmxJP8ETP8CBEzBEGOp8ooh3XHi+jLkFMM4sZJDIyFARiZzY+S9DSiTEjVsGwSWiO+o5nTTIAAwi4oewGDUGh3gqfYLeHKrhqSVd6PLFx079kmmTlehizfrLOIM2VggwFwWsCQiMKlPDgLQwNxwMzGVTDGSbhTK/gyH+0yV8HKFfKxq8gluxESEgsRNO3CsUgYDCHkAThDxz8CQtxop+vHazfHI86WAY4hXIkKPOMoBY5OlzRyEUGCdEzsv9HfSNdsaVJDOnepb1FQagbc0XZrfU+fAHKLlmK0Q8QBIOCgKRh1+GiMDIcTL3kyAl+oHBpvjQdRZOJLidRdkoSAVzfqJRgUKoNBEMqWrPFZAsno3HMKnQlin5rOItFiRmoISMu514FvR+cUs0D5ICXGF+lkFpVwsU5rkPZFPvk6OmHiY8TT9agYwPvSxC8pQcq4JS/OVLk0c08tHPdUgCrMBFinO8PZhFGCaDXK8M35gSYAhVpzIkFavOKK5Gm1UnDwYGj2YgGzVhLCIlRXTP+fi8xPBBeOCepcHnjOi71FnvyJLgIVz2UgsPjiI7RlnUcI3tPwPFbTeEJExdBrFSZe9RVawdoVKv97jdWLpggMIFmnweHYvLjFWrWSaUFyc+d6eOUYFhJ5OQP8NXtKsL5CimjqDhphZxGjSwXlLmCZcadbqWhsCgdrt4v5frq5tHTWlgue3SDMPW4CHDak+Je9fmC8mDTEzVwuJwtRuEVVCFHPJkGcHQb5RN0PRw8wUbXsHARAUcJFwVOowd0npFNCUxQYlKR1DoAU1vZ5Y65DAGE3+mMNupBxWHohVDtTsJM5oyWjPwCVDEs/i0EWwip7i71LFR2+W9NZvDfrQLfYVG2pRuUo0lWNTdp/acnsasDG6mHZJHQvyihch2I5EPNmLPIoezFb8IDHXE1zAjRPsyuwdTPukGpCqBLnSWcNvLsFOGT1rbwFX0w6MEj723T7w9iza4NVkDpoeR3MCeuQHh9NRCQ1pdg8vciYkelLBwjkdi8mEDbWmBQxc7W28PGrN/1WbamEYiQRB2tcGtQ2FAMD8kp5KMqBY0gLON9SpYc86pTMbxI5D4KUBjGQM8BBFXFXYWnYJO0cQWJQJOxHtD3LM0O1q4OTUv6bfZmlOF2cTsanVDlvXcRpVjIwCC4ZA/AGSdOPwFbzHJDra8GIB8+BuvtXAJt9YwVcFF7jIHe2AwSGJ6M+JcQKibw0LJ6D7b9ItF0thIYUlEPToUHSVK4oPrA92RQHYWD/4MexY8e8Ynjaul2I0aNok8OqsBHPbwRifBgEsDNNAVajYQCUKQ+J5TNdTN0hGQngdDcYH3Sr3TxDfcnACC7JqdMJYckvPQouDgTIGfTYniYZIAJi4hS1IsYT7LsN0ifBhTsoIelRP0mlyBJ5jhB7z8Egl95SX1ChANVS7boMqgIdSXpIQQs4YtPzGDWLMN3IQaEwIAlUj5liiZElHE1tZuUIQfg5U0cc2gfsUNMDkYylJhzQaZ84M+cm7e7EJdQKAHhEkB0FE58aiaVXLREGY3sUaaH/RVvQqC7uMtcJhC/93kZurlnDbaaeKk/UYYDHkatSAIcKLF2arx1hahaocK8gMdo0A0/zqdHtjm5X4lZqNO00U4bpCyyNOURgeLKYhI6EtMjiemPHC6Go1E0uBnZ09op4hlEvVnw4m4Z7Hu4uEnLQt6vxg3nc2ByRS0cZZoi1Ebw6VwCRp8pslnBJLmLMLIkbM9JfGgW6p5IdpiT4U9i583o4V7lsSdG87AZluUdR2lUoKzi/55PLMz0SHJZ9UDiiyIy47FNFpxcgEgolxgUSbQcI5/Al5n4QYXr5nDDryGhLFOn8NP/FgCarqPwxmA/acd+VOiXXwAy84yVmoiJ5pN6FFmRQDkgtHPWYoKc2tnI0oMDQ50fFBhvI5vNHB4A842mwBIYfMGCgIrD4ZETQCvSPnUYDQRMAwKKQAGeGoG1WCA3LRLQkQjGDpDHYCL/yfs0/2wBoNFBqGV0Fn0HjlnY/1HGQnjua/3tVTzA+2ElALGqjIpWRg9mVbJSDhaIYWynYehUxuQUSW1gHP2+Aq/msBAVhP0ZGwn5iykCuc5Z8xMxWhkjv4GfoABdZ2NL46KE3XOeYiPM+S3R6gkO0HaLJUn6gZXD3blBoNlMY0kCGylWYSwZexSmQgWM/ub7ehHDdDASO0GEBZw6IvwR6A6h6ExzYe1e70e5vd4d8WdFkFhxM4QytKPwXA0H1IMk6opm2GN7FlCwdCIos0Y3quMlJAT9Xltng1ZV2kBcziHIsbmElsvt5cwWqMLm8eADxuHP62OIwIEMmR6CjFBViecPLO5QXtLnDHXOWC5pfJgIhpTEJKRRUicvViXQoBhDx19byLHM2jIbQiBVYozkXzJIzcXbZTwY7NH0Ak6teDDSt5d+khbO3PWErtVPhk257AvFDBu0zSAyZEw4yn+xsMtT28QwJwzgnLDiCNuIPY5YHmmTz5KzjeqVc4g+CmJ1yITo7wMOsKtDRL4HzIjSMhWZQmnrtQYQPxIgyGQ2BL3REr5zIJOstdIyLI+C0gLHMcK0ZQ381qNzSBiqIMztzL8kwKDrHlGpqXLuQSyV2Pvgg0uVkQCA0HsRqq+jARKoOcKsU28RwMr6uBBfCqpcHBFXJwRK3A9fMFQPPkMxQn48FPqNz95FYYVEFbiHsXKwyOZsFG7Cc8OVVM+FN3uTho7gliuSBn7oaCnbLtYy1ZAObT77ZomeGpGBFOQCCYgiA0iaEIZakNAcE3l1Ed48OJsM5oUYDkxIkc4ibNTAJpAQ/PQKMcHb53LEJxCY9tsOtIVGkY2SIZwgFlM2LRnXMUlWA5Qi9HK3nld13XYZnaPQDFBDDKHOw0yAsoWCjV+7S4Y0uESiAbqT/zEFPUoE65G4nBJyfCizdpZIw/8EDjKo84GJE4mEayqJ7lq5gFzy4n5PAtHr5ZvGptl2F9mZo5k9jb70p7xY1vYN5Z0owgaYgynwAcGiu43zfbgBWk2rtk2nOpQChB8hJKvmOERBWJGwOTYw8GRd8AYEkJ8RSfnt5jjrFlH9Trq1IhBwx8/noYq6BNKFJinsq2muVrB7QTIaXo+foFokcsQMBo7ldNkXzmYNnG4RlgYiTAbyPIDDBe2o4Es+rj4A49OJq1Oa9RKwRaazAnKEtHhY60YHLCYCfXMv2sxLMhmGguS4BFBFXUphoNyAPM8yoGrnCPIlxVtrBioPjXmkRNyZDzHH+JzAlTQdewZixZ2LWO4gsELpPge7mAMAdSK/tOGUY7AibqZgMv/0rQEJoDvnD0qjPdSWkLYFmM/eDWKevUMbk5GhQIpcsLs9MxiKyKM7eoIHe+CIpdEwCMx9EjHmA0c5nnAkIazjyGm+AsWJ0SOG4n9nQ97yE2tI3M/wV6g1eVji/3B2GB+4bRi+si/LY7NPr7f6+BORy27zBQ2C8vbQI7gsVmEtnUT0bBIbNe+xh0VdrdWIaRiXrCZDNSgH0cDPm2qoAB/c6EhLw0UwiWb05gnMjE6A+RKSF+GpgKowiM+A4U3zVz3WDCNSYSzy0CW5FWgB39Jy0FR7EJP+BtKg/e+98O7P/WJ57UOHX5Zv714MmwGK5rdaXMNn5HZNveDbBx44Kw6rCh74yDfuMS8nCtBo/Mnd8DnCyzjS818AUlrl3abAJI5mWh0U02OclcuZ25lRjvQiQe0PHG2UBuADBBJ5qxBeXmiRvHL4SjzrjhCaxh/BOdEq5a//dtzJ332cx8tTzn998vxsdvNOGZLBdl9BErYwnxIo9N2Vc52BQ/yYaNazY6gcZujTmn+5Scjkp+HnM0AQRKMDk4OM8cN4Rrq0NFmHQMRV1QjnWSr2jxnnWm4E9gL496Etfz/67hhx46v1TZu+XCtWT8AB2AlqfoPG2W1Ck4wpvvKhET0WvjE8oAarfbVKBJKdA3ykGBTid1IVBMcmTaenCkYICDyz/0k6YS5bJSGE9uMP5edLHnleHTEHG1TrGpWwROHywRZxv2ELtaf+rQby/EVt/LSpEaM2wImTSYbcizAPCnIjaJ2+jSSKId9xPginlaADFesINi+VulPP1WcyFHxpZdLfIKRZjF9MSe+KREaVNqzndBoh/LSXlCUqRBnqpBJZONX8dJMBiA/UR46VK1Fsf+KK7YOjh49b7C4uAF3b8ECn4ZAj/kBSN4cjU918K46vhiN9jqW024Nb75gEYToCEC01Zq8joPnYcEDz1BbO3vfxV/aoFA8c4I3rPjAMt6PxCzn3+eVPuCDx5hh0yZOYiALvTPZdoSdcY2CuuGKBQgpjks2W/EiiEwAZbAyQ/vW2D0L6zd/8+R3veugeOOw9rWvPbrnC5//Vm1h5jzwX014bl+VR40HnMqmJiPqpB8OJUGErybOGdLK5DCEItnzLPSGzyR0JdCEYUoFaZBYzv0I9x4KiBFvBvtQMOpOqUBhmRekpJfLNrwqiMi2jq+D1PE2nNFWx/6uO08vjkxfXi4sngcH4IxB2yZNwdx1W4TZzTk+2ckXdPmHavg8D5jx3qg6Bh1K/mUMXkHgV0QJd32hGnCBgEhg6vNLTbg5wpgEEs8wbG/O8OLbeiTgoyj5YwbsA/tInuyuTZOuq9OjjShl0azNtg4evmb/FZd9YOP7rroXMEDLQeu3fvMH7YP7p8teD8ECyYmA9rdEBkz0B/0WdYPakbgSBJ5G52iqmM8Fsb4YETqJ9a/HpxUbdTyshcjHCNL3zZy3CVQgSAAZLZWfTned6nhZrrgCkBbMkjbQtLwn4oRsmNf6FY2edztdzAX4azv9XhtB26EDmWQFCJTG8DL4KIAU244D7rJMYsyCwgDkMHVKQsg4wwTUS1ODiZDxGQUckCYeDNwV5hrId4bRRZNugSaVgCCSdm+sNnfsSYO7+98EiQULCrWJ1m6cVh/jdS9gMnShrflIzCFZwsNHaHORy2beLcnkKTWxZa+gH6EiPs7hBw2MQDHmSFHBooriFaE0TnJcziSGVQ7LykEjxQAP7QmvyoTLb4mSbUErvAEWgOU6Dxj+IgW1gMbgKZ/KTzoMybV4MRloCPm0MLion+qv2dhJoYX7mfh6ABJLmi0u4BECxFUVhgtQowE9W1ZxEACFWFRe2H5gvGLpG2t3upMQLgbGnt9spz5a4lKgyE6itT4N60TeVdCwD7I1CiwzOFl3cok53oErJEYlrhrGDtYxxQh8FHGZMDZTONuZoLGMzGgnrkHtmJQk1BmmnCjOxJrcWZxtYuihSCeGJbm5Ilme+BHfEGpGQ9eNwEQxgFwvw3Meicjq6hAGjNYHynG61AcJxV/8Yu+huRkZeKFR4ldpZ3LV4IYBRMqBhwLKNCWMJYOpiEkKlsUf+GGkBcd2v8VVgHfIQI11MHqaMOibZFaUqlqoKV5andgFs01GLgp2L/WLXMxBIuWhgfkF7VAjKScltTJwupMwcbWiKLn4orBcoFBE1U3UQBs8lIOO7LDdFNd8RbJ2gq2kYxABOpQw35R1/G0tbEnZyUAL2e4wqwKj4mpc2DeOVG0k5LGQynb0gQxJxAT20Q/yFdjbQi4dgP82tzDg0EBE7mXEKNxAOlcS7UEuFNKAP4ehc5f0ooW/P9gGb2yCwdksxsVZL5E4ZkUAZRmF5CSufMQsiTSGQF4aMDRhJZf03F+RL3BtGcI1DL4VJ1lmYCqMVgqQYSDbRNjRA4UI2USgNikgyoogaCXBK7gMOPQpZPHBwXaxkEo88bENKmeRiqOVCIMqOHcxXJNdjZpRfNZtnTcHKlCWQwoYJEJNaUw7SCWH0RW0Do/8EdMy2sqC0Exv+rCNcMtND87GcjsoTQjbLQ5bo/2dn+/X8fcNscXGKqgdk59RgdIUcI2Y0X4MQzImT568Ic76eDgfTxhggHcRdF2S0WbUiYkF1dHpCqomaj7o4E0EzCuhMyWE4qI04yZ2Rsgj8ZgSvlXtaFJziBnDIaSxWK9QbKxY3RQO5T0gl6hv5/2IE84M5kswjs4jxBR/nDWkK2soG5DO4t8iNOdJKvjjhBYQ2ADl6HIUxBdAGg38nFBjF3UzbXQ7BaFko00KoNX36WKAKukYMDI6lBAfsEQ04Nxu2F2rz9mwZ+/RY/9lotef4tcM+PA0P2LMJ+6bOHCZxt8lHf5eMDakOJ2nxiW/7NFd7G7tz88/vjY7//hyob0ZA4cdNdNLR6hoA1AmiQOboCMmK1whUJHuZG/RAcCd1Oo0IEtMnAG59FjNjmiGiAonb2M5IUch8hzRvcgmCkPuWY40XOZTW128BY3A4PgBSegwrJ+ownGsjHCWOi4/DxTRxQH00g0hJWeLD0egBaUMpIPpEAFENAtKQPxEAkYHC9OROf4+GJYdE8TNMzftPXA2iB3L1719HqXv5LCfqzwYfPLgq1+9rfuDH7yoPLj/4kG3uxpm406IkYKDjKOesMwgYTiFMrjOUoep2GDjCEMBbey0AOSkBrHi6MNFjeisuLDzwA6GLgl18ODT63QlBDIlOlbCQSwjxUgPPsSOxD/le7yElRXi4YlAz5wRNBVPg4Qs1kg22i4Yz8GEYLMQdaejicugwtFnDaMXMgcONBnlz2WeJwRiJ0Ojbqx4kc4Mz0Y6JvrB+j93wrWi9fgrttD/f+x91rMOl/v3vQJ/r3UNfISVCsKiz5KLXjAYEEycWDh7sRk7Kk7CuZbWMdBUHckUZ69TgwcCm8NQNKo8IMeBsweGmcLMQWkhMTeueJOZJ/6FSfzd4kANsOV0mS9qNL7+0YmRGNxRznIFbejkOWfNHDcCW30RHw8e8nFtiK9faIc86IRG3vjxj3hhzdGVQMKVaDcoHLyIyuVRbfz7zv8LE/rUm3/iEz/SH2t9Hm+v4S+/wkPuKxOMIaihAOtyyGtgcNlkf20M3ad6YQ9DUrhZZ51quH0pqypgvC1NviMGRnMY3KbuLBoztl2eM/CSKxNQNNpHUbO6AnJUSXONdm1sGmoWrU2KagMuhdmsQqGGT9Ox3QaKA9mIFB7X8ERd0wmdgoIQPOesYzMPes7lynb6QvlfdTh9+/aFxVM2/2XRmrhVqnET7AZgnKBfzKQnz8/s3hDCLDpFxapRno1QwdlqKTmTUyhHBxJhFa0j0uDukFiKVJcjQjXDdSaVhTNHO7ehjHsW2FTRbrTOD3Tsj/d7iEYV72wsC26O1Nmg8zw3zTDPQAwJtMV9LCKjbUlHDxieqdFUvLcUe5ZDV1yxurH7zqd0Ov0NPXisiU8W8mvX8CKCixGGj7tgTuBfrMWFGa4W/EPqXC1kdR4GvR4uj5TzrVWbvrjmrLPuKbdvT5Z9yI7rfrL7oouuKvfs2Vz0sAGmD8GDXWKk5GkCFT6FyzlnuEXInHaTDXO6VNa87zUaI5iEhaWyOy8RobAEL2sUE44+e6MJAw1B3lyq3wKM20ycyKByVgSujWAa0QUgD06pZ6FMhWJcI8gdnjIa0x1cwVjy/oOOdonZYyhIIJ/iZCvnIfGk8dlE+O6wyZmZ9dN7Drxi0O+dS5Zt4PEG1qgjsWj5PGACoks4PyYnvqJcax+b+cc9s7N/AL2+HwFBrbd++tM37H/a087rHT50Mfo1ic7hZBXCaDNnhCjGORhCE6dLaiSC94U8lKQ4StbG9jA1YfYzTB7RnfsKLhqfP8Z1lEmV4lwWdjVMJi2Am4iYmCu5IFHizCLSXpjGG5DlzpJe6Lp0C1TI5/jTz/ukJsAV4NRvScr6v7Tzhp3R0SGyFxnjl9tOjjCw9MhFUYW6v81wpF7nqjSPLdsC+rqAWzPI+wuYffjg2jzYzgM+j33FAu6sL8AUC7DZAiQDXs7DbnOYfGbwSfVjg9m582vTR1+26wUXnpTLg57dxuMf/9HB5BSDSH90Xu3U3oMQ8SYf+D2xRE4zLEk0NKcoGRSteccrZF6qoIGyhJ5obs1AjFJV6Wn+kPyiZLVkRUhbM8w3zDaBMRNTxFAggHsELXWhMOmEwpBuwQTekY6Zo9kUuJZThPEKslEVBacyUAeWQmaYMLiYaaahMqx6zrL2K1n/ZBKeRXriNdNcFvmzEf7gxpNn2/xxP4rwNDqOfsAghgVe4FF1cTBz9FmNhcGT973qkhVoT2ndH/3R3eXmzTuKRmsfaNwS2tyCJfloCGGM814+jE5KKmIciMOU9Uq1KmDUvOyh6miIjRlFawrFyKhGnHC4BLse1rlgzo1X9imtAFd5pWTSvuKgjgE3cpERL3MQYWqnp7JfoqFeXonlJWh42yJuXRAWgRo5YUMJsoNH8I+cePmtOlx9iyb5jH6jj7gtKeqN+bLZmMWFj3k8Z7OI2agNeBvt+AQf7sLXGov0O2yKawscVGDV6zf6M0dfVOwvzhxs3z40PLa8+MWfq62cugE0cxZ4sAl0lQK49sOvVWI2p3WqTlIZdpRIgSuUIdZgEvscIxcPO3jAAT94Cc56OCLDJm/6Dq22w8vaQKKm5W4k8soLPrRJI+KfcRApFGdNnQxeUVnSEAhLc9kAF0GqJdMHFJdEDzSyi+5zeEc5tLGAgT0RbLw6GnCqo+srhKHNLSYlXH2V8bEfBAX64n/DhcsC/jcGKya/3li/7T2Ikp3Y15TF7Gy5iLvCWKfKqcnJerFiRTmGJWxmYfbJtYMHX1p2OxsRMByrvXJu9qziyIFLd958834ISQ+Ll5de2j74qld9pPeNm8/pt3vnwbL0uGLBlOEG13vIJSSAYVs6G/iYyaLFchkBLVyXh9rCWkAzHmZgylCd3s9wSJvqmYyQTxGcaxs4PxjWwGuOqKC02VkNOD3QOS/1NBTrG5eH4M2IUu8yuSQ2GjIb6Vsmkl4PGQ42MzqvWFZNaR94CDDaixbhjxc3aRTaXfYMRsjrJT7UzgSH42uiWHHsZW/ggRYvGI2NfbPZ79+x4Zpr0hN1wh85ID7u3vOsZ2wqjxx6QdntTsgbfPZr5ugzJsYa/7T7iiv+btv73jcXZOvf/e579lz07Gvq+/edhGf+NuNZISjH1QQPPvElMz06FtjIaUz+2CWqJq3DwZGrfeSANsOXSjqvFUZGUy0zGS0NHEbOwKnIIbHMRTlucClRtKBPznVebCVMcFaQUlmdsq5ZX609juyHypnurGtAAZZm1Uz3oI3Bx3rYcliG85bOxMoCmDXw7/lFOc4O7J/onQlFwnmtsrHA4n0mBGe3cd75eOC79V1wYa/JBY+LdaYGR4/8ZmPfzrNGl6PNL3/F3w5WrrwBKxhuMdhehTpyGcJWyl8FkVh2RJZMSriOmmMjGAhL8IS5tDDAE0MURDpukA3DYCrT8PzZvyHB7JoZ5qeIyhTRLAV+ucMolyjxk1xUgiynSUEiJBxG3KFgH4EJlbCAI9do5IjUPBLMDK5Z1sdgas96jjPoWnvoRiJ6ABaBwssrWJ5qs920n6kELFPa+Na37u6v3fBRPBO5B8FjGP2i251bePjg0JEX7/zSl7bmZFyOumec/eFec+w2XHaWEPgImw5sg7ij4nwYCmluJLUbPZQkSGV1FK70lTbo2K6RC4CMFcHhDMI5xGMadgyJCK1mAjOkE7Np2WRcicWfpvkMjzKIEcGay0w0cO6obmQhXAVyxTDGGW3DwNGvalb/UwA4XLZA0OQyQGlVLkvC06g3mwPA/U+eclrC+YG5qQU+AH7/0ubrrrupvmLVp4tafRod4+kRZ/72YH7u2VOtxpP3XTJ8doSl6e7Gxi0fHzSb+6A5PtVL8/KSXJZimg4tpCSDBokwtQPIsuFYJwkPGB0W+MyZBDEC40GYQVFAq480M4rPBM5HMFtzxCsO3OAyzv3UUNdM3AWB4jIovQpC08Z0JG/OLBZELhcwwuMygGYTjmb/WYBkkkRvIpcEIySr2ykoDC+fXWAvnaiEbfNpUW8Bum2oKIyMv9qOs68Bnvhq8DLL/UuQ0Rt79GM+Mmi2boEwXOSFND6N1xs0u7PTl7WanbOvvvrqoRjd8Ja3fK4/tfqGstGcxQLEh55w4wqhPypSBgJQo0QbHBpneHSQhoTQ3xi4c7XcyMPWTjwmGQME5JkCRXC0kTvl0CFZAh59iyu1S5PvWYSfRuoImvR3mPh7T+lUEpJuSCBxM5wlzndeeUZ6LqUxE2vWCQRnPsqHzRLDQPOp3MVicxvElpN1GNqKFujWev+Pq9/+9kO9zds+XGs17+Izm3ymCL/OYG7u9PbBmUue+KmPDS9H557bHjziIVcVzcatePq2W+B5GVya43VmklIncxYVl/IjioeRiZunHDeRpEKG6TDJARFz3mllkOTo1m664NpBBwZb8owCQpTBpacwTNlMTla0IHFegleBIr2H5lYg5IpkfFhMTdRdxIbAInWO4Ex41uzGjIrn0J+lwI2csBjivM6C3b0u0SmmsFswmyUyot/v9OfXXPO1wer119UajSNgrEs6OKHuF4cOPKt1ePaJe1760qmc2Unv/sA9g3WbPoqr6Ptw9YbPssAVjHAPFG0I3YCZPcQjZoTomNEMOzoXxrJ4gMBGv48KAEVrVtasktMBy2crQPuDGezlZvL2KJMNLn9LHeodfWB7XmZdSDiwDzqbwUwYSybb0ZL730DZUfR53QGaSQGPfhJF5QxXMAY3dBzlwzbCpK8aa3yxTizG2MipRQsVK5YI+nnSdkwoK84//5ODsUm8aoKvMyBgYI9+0e6Ol0cPXTZ2eN+ZEfDB//bXv/6Gxqq1X2hOtnD6pUcorAvUUCXXhoa1+DcDpA0eOQHHqFghFn4IsggoWYwICUkhkGqkypMMySAFX3gt4SEUoIMZbwgfML4hmMNS2fUYCgbxWIYP5YnQHZk8jWBC/4NnXqZ21hA4rqFjKyLYg/g5E9lTtgquw7ntPKurDoverEDi/T3ahTxj6hkmv1+1VW95y8HGli0fGTRau40ZfFyvtfsLi2d1jk5feuCZzxxaji644ILu2JMeuWP6kaff7nPISL9obLa40WUDKumJyqsDqBMtbCIUpwlHmZHN6II5n6ARy7yS5MIhGFF54Lh4ZVyXdBqJPMi1dwC9bVorbOogsWjj2Fg+wpwPEIVLcuriScGcBY/AbBcO+peUCIosjzaAZA8OQR+GbApbjk5tus7CEcrhQlo4Av9FsuxUm4m8r+LvXn3112pr1nyyaDYPQx/w06zaLhbmLiy6i08dPTta9aa3HDx9+/84glNnsPWQHp2CKDCMJEfDylqmwmi0+qjlh+oWJOSTJ/Y2TzIg6Lh3kQ7OA92AbRQxoyQ4kWOiERXKxo59CVqDpKOw0LaEEWgkH33Kr2KTN3lZm7GRU11cDl/CM0kdLph9LW7ZEkFCXokHI93TYruNq+4Mb2AiYHBZGg+sYJ+HU5nA+XnyHTg76r/gBR+tN8e+gisofMsEdsS7A93eGB7qvqy7cGzJxTrKwTJkDqUySWE00CaC8R7QiGoWMCS3GUZnMexj1U822qjLaGN9p8fsfRpDMyOiLKHimlThzfGiaBtidkRUUV8qn3BJzgp/dAR/+WwmcuoIWpXjQB3xM/U1ytQSzgy9lLOFghRM4E+irI9sydNQULlU72ZCS/0HJDch3rUHBXZYEKh+oB0uxYMI7Se0Vm0+/bOf/ezY1VhE+LvEf1EHz/rNeBIIOX8NwgljmbCt27bxnvU89NOTNLIdbkT2O4sPKWcWXrzr29/elhT0gq60qEPQyPpiwaN2rPPJYDpj8TZ2Ab5IbUCWY+Q7VEaNxzqsYIajE90o4E+ZUF4cw4VEIA4TLh5iZowWg/EINzFa2CBU8iavCGSTVeHnJepehRj1ciaZntE3083aiZcnylC/eVdQZbSChwLIEbmK6D5QRmjy2AMAUTFdwQK4fJGML+AHOpr5uFO1QuHssL4wf1bxk7ve8ktv+8O9xdv+CB8G7BcXiBUvsOLvYPcGtf2YJk+v14sDsC1mo+ICHA5wQqLZcIqJO9Bjg4X5rXhCr4V41IaI4w930BeL2blnNKfGv3vw3/27v1n/4Q8fC10a6BhPu8EDcqwXUh4iWCNvD4rICaOz0J66ZOzMwE5IWgNbZEBPS6BG4Lid5Fx7X4XyzEh8KIErIxwPEEYW72Atl2BE2GRIjRiB1E/dYZDS+KOziYI3Y0oJgFkGWugQgTIkwElkA4asO5Z0/rAb5wL00exHntLD6dTvZBjawXgwGuAF7hX7g4bdSGx1aoMOXw/Ds5OMQPOSiLuDxYWNg/b8ZkDZT7LV0QooQq/q9iuskcmXVGLwzyKgwVTEDW7GGhprvW6jf/jIZd3W2J2D917x1fK338dXlPBWIjwC5NQjWVhVXMYQQ1SEQCRLVFptNApTZhAZBnW9/gB6ozAceSIBrEBeqSNwMCKDr4cr0QGIhkZtsrnMNVw0Dt1DMRp5xovZ8u8Qy6TjEMS6T5B1Ndk2EVQdAQgKho4MQgt2wOlTt42VjRxmkCEUwDgwCHN+ChiiAkh6PA9rhPzqH41Ae7qdJNfk0+q2oUEr4RVT8pcU5emxAdFBFcqxDDQEMublLFTAC+/B1xYWT2ocPfKye66v8TGGH+GHFlwSY4HS1AHkyRgsR+JIRXDwR3CMqAgkwQBnEJFE+xgVWDfjLGekaCMRZxObnZDDSFQMnZhsdMuhi0VkCy1IIlmsK1EJ/qiD9UrgJbMKoCQMWYa09Jj6ONrkUkM4+0yfMi3LM/B9gNuZptwlbY0yO/qpcRvPSgIKE3i3MhQWFdJaD7SxU2vopHZBiEY+jC0yg1yYp8JDKFmgGLYTggJfNuqs7PXm0gV0TCzQjOGFX2iuDnv0s8zODRkuLAPGdGok4toIkCPN2zIQeAMvNrVUlD+TF3KJUxmQI4xffcJCg4dwu8vPLFhEeV8s9A49RnO1D/XPMCLwVYvgclugK85XLgEKdPPBIuXRAfbSe5qWoJDN/jFFnioAaPZw/iqr0Q7Ute6PZLTqOk0FKHTIEKNoAhBQCFkpzTc0QaIgAoQM+YukMjEqzTIU8SGq/IizJnQ6UTfwhSs84kI5wHB6qsYihQfLaM5zMrXO+szhNBTEttE0DIzAciwPOsqMwEWAsa/4iBfeguBMQkd64hP/uNaJAOtgwgIwtdC0NEa4EXX2j4lm5CBQQIAk9hUIAtQ4vnIbqm8cKACO8KvwdLov5tXBbBe2Adx1o62oV1LV+0M4DU2u1C2u4BZNfE+ZFx75ckhoRubhFCnNJYg8wQJIkVgCGoBmWNaFIxMAJtnGKNglZ5PJMhf+4FffIgQFEY+bbOTTGTarVf1elsQDINp4lkAx9sscMIJH47JjzLFtnOg1GlPbjYyAlLihxK0N4clgCAQGAxE4i1Vd8hIDBW2qiTcxyYOodJXV7+Mod5jhqSNSRpMVAab/0I4f4dJLZbeZI4sH+TAZPlp8q6xLuMaAQZSC3rDF2pYY4AwxSn2EMF4bsWXIgpWB4gwyKukoFeRc3rOjohUm2vBlPRkYcw0NVtnX6sY09BiiJGMZGTR0tjucODqTjAAIOAJFDgWN8kwWpYQMlkMO+NPIk2W3veb333F9WjuFXzbx8BYS9SdP6eJqZEEjXgwgDxTSMkVQqRK6qjJ8oF7kYYZOqlVIEK2ZgRBfyjSY0D+LYt4sRXlo3APXOxx9FS3weOrDuT8EyA+hBMTH/iLRsc15GY1spkGjPtI25KvnWBQ0ILVRK8VDkOcuChkl6IOMSRT+9l1nDlOSusmhJdmp2ThUVWsdMnQmhEUowElVTweryQ0YG9/hjjkFOkQZwdcMxK6AT7c/0e/1N03f/pmh1xdwzreIYb6oXkktSVvK3sA8JU2Jciiv6hftDaUBy3/sSdQTcRS8XxwkgcOcllT8kJfPVSaHrYTRQkiuAGsOYavmozgZWuRdZyxCiT9xhcUc80VqQxl8Kc/ZDvVNUwQaNagchyookQDJtKNaZGNnV5nJhIMz3NYRjEeb9zj+BB4+OD+PR7SBS1KKRqMB6ABuAKWzdT86Rm4+MjPDEIpERtwzgA87Fcb00Yoe9pp4SGHTwuHD64Tvh3p9HB8drLVFG8qgjTLDj0RlE5dfdpwBo5/XZQzqjqFs0tGAFHozJzzqhoMeAsa+qjk7UFZKmRKUg6kbzR6koJQDEzJatEcACja1rThDRTvf1IECFXoSAi2gGtvUSYQJ+pZ0gkMAsR+iBC14hEnW57AQhUlnkGVLVeormGM2StKI3Oh3eniLDQ9NQE06ms10WJzV5NhRhixsLCGSHaFodt6Np7MerEMUqvmKlnLDkY5CQcWupdsIwgWUME6UeSIFLjychNcXeDf0h9FWm6wv4JHz+d5iZSBaj0FLnOAJgC5z84YKOyV6hjZkYW7GIOGlA0lBG/PhRAB/CixvkgQAoz+ygeMRhULoOKGg7N1nkzGzUqUk6lKMg40RIIsGkudkIsYVGauQrY8j8n1nftsFWRO6MjbBTfs5vjjERZoXdvt4K0HX6kQLScuJkkROH2yMW9+oNvq9RV0BUoTKLEISflRZMT1hTBQYTLZwGZqOXBsdMTkcHY9pmYGI/1q7w8gZtZ2C0yDknXEHLq9fbwbtqYObb26Wj3ucriYuTo3P40xuVurQSLqYR2NBiOnR4LVrPEp4qNcc/3E5MX5HvdE8gFGEz70MVg7a7ZMGi3MPKxa7p5S97hh3P2WtjteGLXDUl1zBKJN5RIHD5GDozSqCRGkExU1J54A/rEgvcW9n+ppMo8TRz0QGeLqfU254lDppGIrMtGAbHpEFIj4mOdY61m22vl+faN2BV0j2kFHZW1zfm28/pNZpn47fJmyK+HVDfiaMXMiyShIQVfMnpvWE01gsy/kxTudFnxtINcixnDECgJyd0ghKpEQ2HOIpDQkDJAIIcOIaQ6fhLICUsVNAso71V+9gswzj97FvWY1PW5118M//fBNAvKJY9FaNz+ECDO9bcKQ00W/+h5h+vcDlcgTHD+rrN326ccopN+17+MPvediVV7Y185CYCdb9xpvfvPqkb3/7UYNDB55bn5l50qDXXoWlTcFIFOyzTA8pQsjSpH5xUKg/I/ZYik4VDVMBoyABliyjjKL4cDST3kjk4tHTHRk3oWHQcrATPq2HeyErpn48WLPxbydOPfXG65/85J9ceuml/FJUShjc9bn/+p83LXz91l/pHTz8nGJ++lH4bBZuKPJ5XDCyWIVmINFES1KAR17BaaxaMXm4PTs/g7O1FeywBjdQuQzJu9DNu1IFjFiRoaWYb5OsIAgE5EMg9Req0cjCMW1tL0QY69BBZmWp16gvLj68vuuuM+Hk3aR7yEPPn9918x1HgNiG1rgZhr7DyuXk2IHBmrV/M3vaGTvOeO97dwLXVoFXv5oBEqsJXTV4TFFgv1Z86Z7//t//qfXFG55S23/w8nJx4VwYTNcTgJz00NIMGgJoF82uLLulBSdYMHbX+mAejn4aQ2khzqSPi4q2BNfwNXG8f6rWscn6gF7nZTEwpjlQotk0EdcHY63Z/vr1f9077cyPb33nO++B//rFO94BCiSf6dhPwLmo8CPMnzj0h3/4ufY//MMLi/33vrTo9tYjetEGeRptFKPekQMF17FUJ9c15mZmFluDPt5KI5CqGx6PLMphIRh1GocrIDnIC46fyBJrIHgKEHPjhwIIdIbkhpHCwo/4cWJk6EqvWFx8SGfm6KP3v/GNt2wsiuniyis7vU984gi+iQ/d+1NwSqM2MXlXb8P6vxi8/JmfPuPS180X731v+ZM3vGrL1K695/en5x9Ve/bTt0BwvWzVD5fP/407uuvW3rL5Sb92R3n55fMw09/f+9zn7qwfOvDK2sLcr3KRgGR0UXahwRUISSt2Bn3wTGBa3FNmDnO87Cbkpf0jmRMMerhbV6/bCUevtRJPvmKPwRcSyQYCoIiWnWLFxL7aps1/0luz+YZt73rXXPGudxV73/SmzY077jivPTv9yNqFT9+oK+DPuXBfsap1a/Nh592ysigOlb/3e0fR1w/sfd7z7h7s2fXaot05FZMTt/imAnQJdVjEO7HILDVqg+ZirdU53O90oAiDwDpHCgLIIWGjzJFC0shZjpTjBWw05ykeGTJoOHvZsK+wklHJzIVzNcN15slivvPL9Vtu+Rpa/pGj6N6nP3tftzl/sOh1tmK9vqe/YuoDR1/+ik+dixelDr/2tWvKi5/3jO6Rgy/qzy+cXXY6+EsM3ADweS/ogLOO2r69Rw7fddcXD13yvI/8aVHcuvW6626999ef9h585R0feF98ynB0VDqq7/JdwNxmUfU8uqDqcYxDXjI8kOSwbm9lvV7+8vRll051DuzcCJ03YCOmZN4c1PsTY4cbG9e/ffakh37hlLe/fX7PH//xVPHlG59X/MNNl3YWFs7A/WY+s1Ig0nCzBLY+UO91du67+9C6NZ+4/Yorrju7LA9sLorPHfj1Z/b6Bw68Hk89nYy5CrbhzGIJyxvm4bIxsWXT2j3bt2/avArsdj3l8afg3fvXFgsLF8GKi7rryyGC/ktHUMNVXrTcppQqYCzoIQRYRKRACzrHtyYcvQAEbAYwQaEdpjI4cpRUIRPyQpBUcQ2j1uud2vjER5vnPvr9a97znsMHXvKSh7d3/uQ1g/nFX+pPTfzl5AWP/eD67e84tvuSS05tHd7/strs3G90u23MOtjXYGHhV5U42jTTUgYelsFS06yNt24r167+s3Wve9MXSjxzuveCC35lMDf9u7gY+EhYD3dDXEcpygP0Nq21XGuGZJ06JxwrOxpEVjMTl7BAy3kTCqtjn41fA9ML9io4debdGJhBe5R62az365s3vXNm7dZPnP7BDx458MqXndS59Uevrc3NPg164G8r4o4xCdx9GJXcL1Pheq3RLMu1Kz9X37L1nav/4sM/oRJ7nvGMl9SmD/4fvU6x3h6lIS4DBY31erdWbyzgPKqonXzyDxAbU/O1Vmu3hhuenVDnMPSqbrMLllLHfOVX3a1BYxCLByPI6YyeDVqGgiPHFEORP0l0p2RlBirRJavXG8OLlxf077z9325Hd8Y2bDhYn2rsra8Z+8rEhvV/z0DZ88pXbqodOnBZb/rY83vt9gRo+RdcoJf+GBf/UKX/uT+y5GO8mIjn5h/RPXD0lXve9odPJt+5X/3Vr2OTfAP+/MW0IhZM2K/qR62sT4Qpoe6ggLgtoo8G5kySEFBQnRBBqRLJsKXv9nFRoOR1pJ6GvOG2ionxm+fL2o0MlKPbt69buPWH/7E/M/MMnM1x0+ZntrhzVgzG0L1xfA7IX12sg2ev2z1w6ML2T+5+zW3Pf/5pHKitp1/ymXJsxTfh/w4k0wHYxOAP5VClfr/e77RX9Lud1TiLaNQOb8TXgmqNXYganFFDVfy3qKTO5ijQWadYiBQBwyCR071BZIFEdpIPqCUqQXzl4A9jeQsHemXIfPSpLDTszzudU/tz7ee8+sUXn7Pi/PXTE5s33TJx8tbPrP/d190BvPrgrh8/ZTA782v4xmuLMQIj4vwRi8/k1K762g03FBs2fbpYserbuEk3h+HXwKUWbtO6vcX5hxfHjj7/t1784jP5cb7Buo3fKvAn5wZ87Yv90wAyVelg9QvwSuPUjVQgDnGFT/3xw+UpLb9E4ijQSEgUQCCMuCrhSBrWONZr+B7L1MSnyuaK3XyMcvpLX7oUX3R6Avjzr+giprBwYP6tTU7eU1+77vP1Nes/X0xM7QIM55TdOmyBpzJxZe3YsWesmz347Lsuumjtut/77aPluvVfxJeVD4c2vOKAeIFI9A7McU0Bl/TKdu2cc5+60Gk27y0adTwwjgs5Uo/aMZkv2VnWIrcy6h4wo21CJhDJaJweHacCUoKNNHZoyHqWuAS5smSiH3WDg/GxrPlfHhw69Py5r96xtvPYp9606ukXfIXLx57LLz+lPzP7y0WnjSWZu3yYsFlfLNetuW78kY/5nS/+/Rdes/X6z72xuPA5Vwy2bPmDYmwcwYA9ALXEfI+9zWPKPbseO8CrnIOzzvpJvTl+G/7kHC/7WZfMCtC66oc71hGyDkjlKpSszxY4tImxMvxkD1bBG0EOJzHULVA0sHC6V7Qatx2bb99+yo4d8++48spTi9ljT4WdJhHJhlKrYzHZ+MH6U57wWzdd8arXbvr8ja8pzv+llxdr1n4I33OfhVyeeg0ww9R607PPHZ+bO5Wyp8449xv1GlcXWkFOT2NDb1AQildda/h6IT7cMdjXrzX3khn1tTXPIgv6ql8aSWzMEhvQfbUT7IgKLdCxr1UKALuFcm4gGk+ceJrmRIRJJurmENRBCzgmW1wTmp599vxd915cO/TjWnnZq/WcaPfgwdPwHZKHYHGxeQBdxsj6am39+qtWv/vdd1zKU0hw2fKGN8xuueZT1/cnJz80aI7twuJbx/4JRuyuK9vzj9j3yas2bH3b2470W+N3DuqNY6BhVGsecV08OHjNkQ+rMXkAeG5GseCI/sL/6qeCTX0OO1j/jY/1l05T2ABoMxQmlmbz+yuKsaPE6+y+5zwovZFTCf2FjU6tv3btJ2tjE1dt+IO378K1Fva1t/lP/mTvpre/40/x3vKny0aD32IBO1yWnO+c2inaZxfPfe7E+Asu2jcYH9+Fs3N+slyqUz4L7BxnZzzGOamOwsDTjfH6j9DMKRm2s1nXrGDeM4eC0pM4RkW5Zgl6c/jHqrEYwmZFAcPg8aQnbRF84g0atWeCMANw5mPA9PAU16ra9JEXD77yrUsPvfGNq4Fc9mZmNgy6vbWcvFCv4b2YI4OxmCvnFQAAHPJJREFUsX+68z/+Xz8KGZHDxv3JVWu/WTZq30KX4S28+I2pHcy3DI4tbISc3mKzNoO5CfuAPr7iWEzALuPQYRIaTCJIphBek/xhKUMZX3pEGZInIBz4pBlMQI8J4E5CxAQsO4GRanXCRUd6/PqkNzrsGch/EhvyKeJQfq0+mGgNeocWxhfb4FkvpudOhT7Yk+EiPvYlZatxuLlixY2bzj9/yQd+Sry33Ni64bPYzt/LEEA80CXNZrc4bU/3yFT5hCcs4tv/+2F/rpITOBvA3zvqTnZ7PcpXv3rQQ5cK8cLRTDF/7Af4fsuz+Q1WDxJaXPd/5CDYkz7XIAMOjc4yUOBdWzJsBHhbeMVz0qYUFXJRcIi1msWYAwUNBCiWACScABgVJ1KMlqJXW+ysqfVmLituuaV5xxvesKPXWRhrdPEqJsOJ58hl/Rj+/taBxz32sf5QKzlWqT8xcRjnDntxfolNMP/iBgcd/2JLFxf5cIXvsqkfwoBX4229TbixgnkBUx8e28MmGwrqjx7KfvrbR1BUN9gwOvF+Ml9SrnXKeounffg76zyvATmuaCAioDvZc6HBVzDsRW5cWcEpByyPfQe0xzoBEiSwgVIICzymNjO+8mundjpz+APi8GUXAcrPSIKH8toxvOZ7rPz93+8V27cDOpLWbNwzGNx5lMs4+GMjVisWOouT44fwmDYGTu8lL/kaX2bGnDPBZ+366IJORpBDer1Ys2avOrum2ZzbN9e4C+vPLKTj+7ga3fSPEiOCniJAox05OGnCYC4vso14kehZEQRguJo3QX3EG/AYj1QYFiAvBiEEo8UChyhM0oEBinscWDrWFEcOv3zl179+RmdifAEvSeGxRJCDD9wyia6uvBr2vBS+NOrqiO+wtfAgGmcC/ClGwrH/h7kWNJuUg5OuKm4HkL8HWqq/jRf7sWHl9lujquyNj9frzcGb30xTCpQrjVeE8AdE+rotIhL0F+jt6Skj3/bRj34Z+PwdN5mJduxoI5p24wuIe2A4/BV54NMVDNs8AFwvQbm/cKdGABHOJKfykKkcjmauMtrEHzyiTlkcKlIKB05a5Jd0yPiRt6mIMdDDTHD0yNNrR45cCOWncAIDS+Kzfd0+9iCLj37a77xiyQtT5Dq2f/+ZCMZHaBpnYOJKJiaDfeXk6kNsfwCnPt4mPIgZC38sFubixL7Y3txZnD7nwN13L3m4nf1o/2j3ozAtc+OvF2swYXWLsbF7B/XV/AzM/UryCzExxRwq+R13TjlMCgQ4RBXL85kj4BZQjpThquiuZpn4QRM54RkKqxSri2dJMUHZgMDRkmUA6sIgRVRgM4uwwTir2xUJztu4AkUIFoa5+Sf17rj7mfv/03/C1W5PoPvxZZed3e8vvLDs9s6B+TpcU3HmND0YH/vR/FOfuj9QH5A5Ahub9u/B4TN2jsvTHHx2/cixF3YO7Dn7xu3btWKE7ne+9EWP6B07/CLcXd8Ag8NYWPBa9YPdVv32M1esmA28n5YnX+HLhZONH915Yf/o/v/Mc3JO2myMAMkdHEzlPa8EnqoZchJQEVkJONGmhYbLGRKDhGuBcs4sHPGMC5aRKJMBlSfAeGkI7aYFdisqmBoIhSb2LitXfmWwdt2X8YcNpjtHD51dHj38tHJh4Wx+PpT0uMxZLydXfL1cv/6dG6+59uac/wOxPHjXu1bsuuqq/6exMP1UXCFo8JOeMEG9HBu/q1y56lr8pfmvd7BD6h3cd35x6PBzy8X50+wUkZYqW4NVKz/ZXDH5jo3Xfm73/e1f+IuDs9x70UX/pnbk0H/tzc+cgc0YNoXmIDLL/C+HEUZieoUOHAoWNmbB4IhVdARt4JARgiWfTbCRVfRoT0R+niJYSKroAFzBAgtwzITGrEkgsZCw0cde14YVr3ZiQ4vLTrwWA+Nhz1KbGD+MS/7vn7/g1z9+yutwE/JBkHY//zlPauzc9aZ+d/E07JTxJ8s5rHgVEYVmQ5/673X0rA6dhIuwPHHA1d3JybtxPeb/3vK/v+zr+ODgkr3c8bqe/ANbD+rjvQOD1RPfgF0T/HiEFByuYU4n8pfjpwoL8Fnerjb60XypmURrEKYNBkrwYRCznHKFA+XRyZYgH9ZBpFALgOKnVk66+I9ndrG1QYTgISdIwNvTGAwcaoginEQuDlZO/e3EGaf/3YMlUNi3bX997Vd6a9e+v9Zo7Uf/8SwYfIJ7WXioqosPJfPZODoESyy6z6WLM8/E5NH6mk3vr2+b+N7PEiiUNxQUG04661A5vvIr2OjiQpRsTpwquXcsOBwsr8sf9AnJDBIec5oheMUxlRggvNzPm31k4GxVYKAwmIXMNQg/nkFFsBKORkjyAEKFJ7qaXEREOEzIQEMb4wOnP2CK3/jk3nLL1g+Wj3z8B6fe/l48XfYgSjjl3fp3n7+mv3nzfykmJ3i9iGfvOJ/GTob2oBFYly/w6MPqtd9onP7Q39v42Mdeu+ndO37mT7y4KysD3fHUZ525ojv9pv7M9BNh7TY3sHCL8OgwjXDzjDwkbZw8AiJ3YnDmciJeHp4q03nLJfBXyltRlnzOOuAVZCyEXOXAk47GgM2YPWA38QJGBDPboUujgcvgjebBXq1+BI8i7sd3zPdjZ3y03ylwQa7fqWO8csffaePBqmYTn7vGjRE7BYBgrpwMPB55H4JbPdzZxtzFP2bS6eOL+mgUOkZDhyXcacGVP65/SAhZTHW4BqyzQJpayIhtXUDh9Q88GQ1WWEPAFwXIgBD2BlsUXHNiuYezOPA4qTFz5An4IPJG7uB82EAGTEDDrZza2Vqx6n922/19eDoDzoANoRNnHJ46Sh0cavjQYLFmy00bHvrQH/PqfsCZD+2aCVi9amxvZ6ZzI54perwuG2GqpvHJTR5S5DjzACZR5GCJ53OcKVjjQYUIFENZ/ighyzcRGtd3AoN8GZwWBJA3RM/ZBxi+FDHWaTlTBnBMNv1OdwrP8qwEJR5MRVTNwO9uPMLoVLhFXNAfkVKED1pY1wQajtykB1yxQZDN4GetrsikGoD8ugFHHdv5eQ3xJB61YwX/FRxoQYTIC4CYLokZbQsl4E1sxmQCLD/8Aw90F4IIzCRAwYBN2czstsH0/AsBxqcnuXehOiaM8igfsdnCzdPvLHT7Xy3+6q8sninZ05Jg2XjttdN3Pv3pN7dare+XC/P/Bkz4VyagDpWj+UBp9jEWrHsKp7GTBOWoNI5sQY9RM3XWkVg9XgITyT9eO+CUk6mRypLncljmOJKReFHfEoMJZXvalDbnf8Y0RjKvtjqaI1MXYNANKSrRF8MSteNj0CIWtJFCLmQikdj6Libgg3+wTC4FlVRnSPHWEzsnOAOM+LQIZhkW0D/ic/IUEq7+E11JjBAYJEIkYabsYgnmtyfIGcQ4wiJUCz8wrbfxd4eunVy7+S7Cgk3ktMuShLvQu3CT7TM4R4jBRFZmDVNpCQ3lSwfKpUc40QnmqCFaxnKY98ozA0aFeZQd/b4zGq36Wf9pA/6MlXUWdS3lrpBlXBVDIt8sxg4/FLYgEw+CzMasZgkNgGsfhUUFuXzHnF4SnAONSyhzOZkCoTHKJCbcygZnHZcQoDJcQJpqSmGASFspTJ2Q2HfSqEw5jFaisZ1w5AguTEK8mC+h4kJjMAGvUYxP3F6bnPhHfMBnWsCRw7LB8rDrrz+2OFb/aq01/g0ISq+NSq4zyMsMiuCrgIGiaid3Di81VjjqGGDqGXK1iyAqIsgOpDU+xitrQpF8cnjUmYeMIQoYzxQ0KEcpuHPW0aqSG0VWJp9Mv+BrWnkbcYCMMQLPoEUKWTnRUlzwUTG0Qx6CAFcsoy5UHMjTHwggULEj/4tGEk0m+Y8m0pMD4NIPOfnSMPiPImYWhk8DT8VNrvhsObmGb08IhWh5yu2Sw4uJk8/YWeLCDZ6h4MPMlOVC1fXELrgyAOIXjNjGXwQTleJYMeW5OzRePKozwvUDCTncsdVjkQiiZxlpCP84dSGOHpxQg0ujnicQCBS6Ri/Z+8ijTvQMPMe3d9AR2JqmJR76Km/BLsqhDrWUl0ln+kk0ypacJlWJwxFO77M7sAq5sR28DCZksOOZnJ5GonTg2pH6GCWyJEcgEXqzl4EQeufoFNXHqzSTk99cWD3x1fyzYImJF44bLPw7NL3J1tfLqZVfxqSMv1M/ktQ9kwp50nsIgwQw5NIG0LjU2ACzw0ohhDlhdKO1pJwBo5EQcMig42yqdiCzfLnLwGIk3aS78UJ8SFfqix/L/vPNLvsBIskxbXPnmGzawH6yR/DwQSQVyGIZWw3zVo8FCjiIZEczk9qXGgYCqhnEbESZ3DhJttqtBB3QFaBTH2yK8KJNZ7Bq1WcarRV6JyvwR/PjBgsRt244eXd35ZpP9Mcm7kVU8rwPUBrEfMlcKakTgAqu9ZoGs5lwBMGqHE5iYdYQMCsuoaHBeTpK3pUpCLClhDn1jM7BKkCzX8WMdXN8BaMeoHVHMwikh/SzfsslClggWmNypOnsYDBdUjeAxBltLpllCPLZyfQgiHIxs8CpCko4mbn9LIiIS9aiIRtW4pcVnd5mIe8TtsljxeTkV2drzZu3fOhD93mfKOxJEUtS+T58eG58/Dv1yRWfwAkaAhfKIVItgt1NmVJiACWWTVROHUeOUW9oxosdI5uUUGG7ZhEBzYFBTxD/EI5ON6iPzzYg0HOBzlxXgoMm+IdByR8md0kSYgdTLAN4UXA6BQX2Q0vHUrTjQypZ9Gw4mPjUTT/ZR3geSywjuU4M+oSrBhwMAzFmuER1dLVZ3ZBoJ+ITxokXOa/o7q6vX/nx0x/1qPucVYDOif6+E573PNRptf62vmLyy5DekixQ8XJUUgosGEDi5MpHr4YCKwgoNZPsJNZxVESTgrLiLTzwgI9hGU0MKSdr/dgoRZYeSJ/LwuVvLVbQNdsiVHTRJ/aFDwJFPWEsIyjHsYDI1AGHtE8Le4WTGSiQQ1nUkT/0KMwYl3NktjCd4ZAGMlIFZFx6AAubiBX1J54nnV+3mr1i3dqPN6fWf3f0Alzg5XnIzWFLyqdcfvmdg5Wr/qI+Mf5jTP2tQKBh4hcjVm2huCOqzTWPka4mly4DBg3zTCuOGIKimQZ0tsqG5BKPRskRUKbM4BFtzH3dRpHtZsdwduBJHppyvXOZkCZC4uc/0VEGeCd8Z5rzothUJydxM7rQBVBLxI3+axaKBs9DabQlvAxFrBkwCCYM9uZgasWX+43y79fitZIM7bjFzC3HxSl4w6lfH/tObWr1/4sXlWbRO2wZljol5yDF8s7ljXl5JGD0KJ+3s8Ps/2jHWaeBAx54JMtvQtLwQNIvOcR5q02GN14V2GLNeA/HnWTSSewX5Wc65PShV/gu2phXupJ3FcQVjvUrpzUbMBZNNm4swGosuw6uE/VaNtFSwOFlfUrF4KzXp1bc3li75oNb61M7l6VZBni/goV02667bm5+7dqbinXrPlA0MH0xNhGlXI44E2gvo+lPYQQrUC+6CinvhBtacD+w6/yRXw6/zzINRJIMiWX+xISHaHRgXByDlQHBjzj4USqNSRhR+Vu6XADoKYIh6sTPE7vCRPZ5Ip1EZgRmsko28U2HyhYeYK4pELIzvYyVRBmtijowPCqZbMVAnxg7NNiw9s82bDnlu+WOHUsu61fUw6Xo1zD0ODXuXwYTU5/AwzU7cD8Lf4mTxqUuCBrQYKHEFIfrIuDKuoKIsLxHUXZnm6uMB43AB5+WS+KXNajOkeJ8NGpwdhQoKgGJePylYHYEIlq0GECEYmp10UB3wyOP4M2zLOo7nCwQDGe0CzFocKmdz9CAFj/nELgaK5KhdjDPRZh9Q6JaQKizQerIgek/8g5K09105f6MTw/2m61Of9X6v2quG/+f5TvekX2qJ7gfP/+ZgoVsNl977d6ZDav+sly1+tN4Kh7fDaeBaFRTyhSlMeRHuLJqY9CglnUsd0JlHhphVOUlALcIMwVMWMgJTRs2QmbMWPRMhscmAIZYW3/YHTWKm8GcsVhUNDmx+mY9TA4jVdCnPAYKdQErDjKLe1OGSg2PMHK5/4m+SEEpMtTwv4/3p8dWr74KHwy7dt37duj9o/vPVWP/Z0E33DN2XHf3oc1b343Lw9fjoeEmVkO/98pgqAxJg6Pb8psiH3MuL37kBibHMGJeVsDEsGMDkpYRBhJ4ige9LYNnPANmJEbnOhHVjJg1ClbVk27Sm7pbf3hdBxqkZitbO3HIm4kbcv6z2vCReLQPOuDqo8xrRfwBzjMUtURwD5GDmrzJI+CawUmxVJ6bRZhA4FsojcbqNddMb1j1MWwpDgSLnyVPcn8WosDdffHFp9UPH/wdvCN8ETZdmGJx6U7GSLZTBykkFxTlMHDwE5zTa9754yEH0WgOpiQhb+U86FfpJLj0NDx+OYJs4syL5dHEKXgkdodQKI/LU1zvGGpERTKJA39rJhRCtqRpEIE+C5QKr+IWtmHQW+AwzMjf+mc2RQ0RqcDlI6NYf+pr1nxs34qT33/OX1/Fj/r8XIl9+IXS9y6+eOu6owcvx6sYL8H7/tASt8BzZ5v2MhYFjQpURx1Hnc+DxZE5K8lwjgcuKrFZsrhLTJ6sRpkMGqPceWiG8x5HABie8apCypGQ8UXxeIIvoKRhOXQI1TitBE501pwK/tCRZ3t5EOjCotvLlksGAT6TgQy3iMCs6k+sbcvZkDJNIU3ynH5QxW0tMOqtXnXV/NTavzrzk5/cl3T7OQqjcn8OFkVxzyXPWjd+rH9p7/DBVwy6nRW49NTOOxnmo7BcIDsXzqMBEw2nZdgJEEOP0cYxZBapLKipGIw8WIKHyXIeQ4FCZ9hUPhQs7DmIQldWI3HZSLEIoPRGRqeaghYhDBT2w5wORDQ6LqkMlUxDVygwtFmOfgam+mo8qDNxLWDAizhoF1fklEl0PkyFiYT7/UY5MTbdX73hz8c3ND659oN/c7+upVC946VQ63jt9xv+LfyZ182HD/za4OCB19YWF0+CPRZt9LmRvOPWRwsGdpg4gjEQkMKREgwmrLNFQeV1tol3BIqQ/UAcUCSH5W1epqAIFIJMT29cJls+WEbDCprivg5nCkWIMVZRHTO3Gnf1w/pEGzgqAWYlh6nB7WZ2sYAwCrNNyAob8UkaxAsCZeLuctPGd3XWbrmRN4WD5hfJc7V+ET6iHVxxRfPA4X2PGuw98Kre7LEnoCM8h+deBsPQRjMRj+cc4cGoQ0q58xkBpGUoHDdQDEFH40VZNKrLd2fYZtWQNdNbsTqGAi6RwUK8cJjtbUIfI0skTkOohb8Fpmmho25woltEMGwQi94OnLCWJJtRKrBmNU40vFABfDHi3YRGvWysWn1Td9PG925+2Lnfvz+X8Suu911aRq37Jrg/rV/7zd/ccvKenS+pHTt6KT4cuAZd0deXgjamzBgVhA8pwop6H+YOyqU50YZol6IIki8Pgc/ZJQ8W7ifiKicD0oIDOObSJZyPK9vxc+0lM/WLcj3onSub8qvX7BT3STGwkg6AR5k0TOQFWc2yNXZksGH9x/aetPFjj/6zD/1C+xPjPHwMecPQf4ba4Morx/Ye2vWY+p4Dl/eOHH0SPn6CEYC/Ow4nwL1mTjcqxQ0p4gapYJXZSRIGrNSs2gkznKqVewQ5h0sEEvkyUCJFwLBRm1kuY9TRFbBZkcO4gosR8A0WnFy2N4ZW0Y8YJKM0pDad3C6o46GEVKEuSR4RVTHu4IkPkELrFVP/VGze8v7Zsamb8Qmx+/3+MmXf3xT9uL/4PzPet//Df1i7+Z4fXdjbf+CltfbiQ+EBvPCEr1GAk1nDjJIHgMwQ1tHoqsQSPISL9qq1KiWg5vsKzjHIERx7ltHZRZgiXhosbKOj6dlw4FLHR1AB15VgJp1R4MwlGYKZ34c2uYnKsAKb9HFabrGCT6LhGldtfOyuctOGj9390HOufdx/+28/1/WT0Oen5Unxn4b4i7QPtm+vHdyzZ2v3ju9fXMzMP2/QWTgJp9ncDvKxFKWIjeQEjm4A2R4BMjR1e4PBDMdZiSbKcqbvVXQWgugImYEjR7KiBlt+UDE/AUYZUkL6eDt4Ck66UD4cHZMCaMXSOkDMoZTIHBpBk/pEFYIXcAjHiTE+9YBP77TG9gxWrvxsedLmHZsuesGdP+vbhUOK3M+K+nI/cX9hNAbNvbt3n1y7+4f/W3H42PPwOYxTcJeYQaNPoNsZDEMkxhNKnPrhmAiiaEsOdq1oyNwn7FjujOU6GjDyJ67Ri03W11wXA4t3EBMEQvznxpwslExfo02oxEuVwEwEKHiAOmgkGOu42drAO8wH66tX/139tC1Xr9929h3/nBvYEY2WVI+n+hLEf07A1ZdcUv+NjRu3Tf/otovwbbhfLxYXzsSXjJpYnvB9fTt7oryYsuMKKz1hQ9zUthFojiY+ocnABCyTjBIB4QXzrwUj0U2GE2ZLRrQxZ1RwdTMWhATdcKCxlvQhY6ShiBJAYOHhZAZswRVdIh6AZNHkG0y4U3xXf3LlDc3Tz/zMXb3ejx/Hpxj/hVPe339h0bAFbPK9N79u7Zpv/PBX8AmMC8vZ2fPxfbt1OCXhi9zYDLsTYhlBHTDOAknvasYxYDgnECgDvOSqxE8+AL4jsTFmqghARc3IPCAmtBLojIYVS1EPPoRKtgo4SJZtkE0G30akCvlswsv9uvjG95Ya+B7ebDEx8V08zXb94LxfumlTp7MfM8nILowC/mWSm+tfRth9Sfnsn145dt4t06eXO+++oD577CL8iZfT8BWAcSwR+EYb3vjE/Ztc2eQ4Z2r+47xjg5Lg5KyRYAk9kmNzxiJ03zoigpdXMCx+ABOdBJrzR/klud5QsQcfd7V22KY0T5mpLP6UCZ5DbzQWylZzZ7ly9eeLzSd98fpzzrn9Zfi6Zsj418yrfvxrajEi+9Z//3+u23jgx+f2pg8/sd5eeOxgsXNG0e2s5JyC/3ytWK8Lx4zBMxq40OMn2xVwNvf9SIhYEmQxa8XUQESUaRgGnqoxlj1guBENKcTRxnSEnnSWqoDCsorrq1wBwRaPl6AvCA48FtRoHKvhr7PjWZNvNFet+sq+h55169lve9vB6F9w+tfOH5DBkhvlW69//dRD9+49dXb/wfPKxenHlO3Ow/FJgy344wQr8YVHuI+XMPH1OI5Z29CYk+E8XqnFmYOmevqSQRD7oJDBYJLvGADZrAQy1UnHmUL0KOtyPnMPTosmCyyDWRjFEkcYIHw3DRdDcH+w1N/LnMc3Mff28dFmbFZv7q7Z+I1969ff9eg//mP+vcoQFSo+YPIHfLAMWQpmv+2tb12x8s47t7UOHXpY99ihc+sLi2fhi7WnaK/T7U3ilByfq8dbhrgPjWHMB+94sxeBpLuxAPCNMnMIl4IwQMCiTrnyGg7LBYvpBWwsUZzZEGiYYPhFAy0w2JNjxsAfpsB3qedr+Fhgv9G4pz4x8YPeilW3letW//Dww0/e9eErf39mu79hYPwe2MfcNg9sTY+j3Y1Y6x/zkfes7HztO5t6B/afXDs6d2rZmT8F38jdhr8su2HQ66/Bozb4Zizuwvbxjdxuv4UPAWvrgIeOOBtxz6BXZPFqFOLKTJKGN7aciAQ8PAS0CC2+Q8WEv5qBpjZmm0V8uW6uVm8ewkcMD/Qbzb2NsYl7ilX4rVu/s/Hox+/54XnnTT/O/2TfcbrygAc/6IPluBbGCL/1e99rbNuxY3Jmz56pVa3B5Py+A+tq3d46fC1gJf4Sysay0z29Pz+3pd9uTw66bXwoGZNOjV/MwSMJmKH4AnRZby6WkxPTtanxgw1c48Bm6Rj2UAe7R6cP9RtjR8e3rset/9ax+rZts1954QvnLjzzTH75MnY5x1Xvwdjw/wEJvSbKEOPp+AAAAABJRU5ErkJggg=="


def _passcode_ok(supplied):
    expected = os.environ.get("TRIXIE_ASSISTANT_PASSCODE", "")
    if not expected:
        return False  # fail closed
    return hmac.compare_digest(str(supplied or ""), str(expected))


def _client_ip():
    fwd = request.headers.get("X-Forwarded-For", "")
    return (fwd.split(",")[0].strip() if fwd else request.remote_addr) or "unknown"


# ---------------------------------------------------------------------------
# Same-origin static assets (CSP: style-src/script-src/img-src 'self')
# ---------------------------------------------------------------------------
_DOC_CSS = """
:root{--ink:#1A1A1A;--red:#C52222;--red-deep:#9E1B1B;--paper:#FFF;--panel:#F6F4F0;--line:#DDD7CB;--muted:#6E675C}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:"Helvetica Neue",Helvetica,Arial,sans-serif;color:var(--ink);background:var(--panel);line-height:1.5;font-size:14px}
.sheet{max-width:820px;margin:16px auto;background:var(--paper);padding:44px 48px 36px;box-shadow:0 1px 30px rgba(26,26,26,.10)}
.mono{font-family:"SF Mono",Menlo,Consolas,monospace}
header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:3px solid var(--ink);padding-bottom:18px;margin-bottom:22px;gap:16px}
header img{width:72px;height:auto}
.doc-meta{text-align:right;font-size:11.5px;color:var(--muted);line-height:1.7}
h1{font-size:24px;font-weight:800;letter-spacing:-.02em;margin-top:10px}
.parties{background:var(--panel);padding:16px 18px;margin:18px 0 6px;display:grid;grid-template-columns:1fr 1fr;gap:16px;font-size:13px}
.parties .lbl,.lbl{font-size:10.5px;letter-spacing:.16em;text-transform:uppercase;color:var(--red);font-weight:700;margin-bottom:6px}
.fine{font-size:12.5px;color:var(--muted)}
h2{font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:var(--red);font-weight:700;margin:20px 0 7px;padding-top:12px;border-top:1px solid var(--line)}
h2 .n{color:var(--muted);font-weight:600;margin-right:8px}
p{margin-bottom:8px}
ul{list-style:none;margin-bottom:8px}
li{padding:3px 0 3px 16px;position:relative}
li::before{content:"";position:absolute;left:0;top:11px;width:7px;height:2.5px;background:var(--red)}
table{width:100%;border-collapse:collapse;margin:10px 0 4px}
th{font-size:10.5px;letter-spacing:.12em;text-transform:uppercase;color:var(--muted);text-align:left;padding-bottom:6px;border-bottom:1.5px solid var(--ink)}
th.num,td.num{text-align:right}
td{padding:7px 0;border-bottom:1px solid var(--line)}
.executed{background:var(--panel);border-left:4px solid var(--red);padding:16px 18px;margin-top:26px}
.executed img{max-height:64px;display:block;margin:8px 0}
.sign-panel{background:var(--panel);padding:22px;margin-top:26px}
.sign-panel h3{font-size:12px;letter-spacing:.16em;text-transform:uppercase;color:var(--red);margin-bottom:12px}
.sign-panel label{display:block;font-size:11px;letter-spacing:.1em;text-transform:uppercase;color:var(--muted);margin:12px 0 4px}
.sign-panel input[type=text]{width:100%;padding:11px;border:1.5px solid var(--ink);border-radius:0;font-size:15px;background:#fff;font-family:inherit}
.sign-panel input[type=text]:focus{outline:2px solid var(--red);outline-offset:1px}
#sigpad{border:1.5px solid var(--ink);background:#fff;width:100%;height:120px;touch-action:none;display:block}
.sig-tools{font-size:12px;color:var(--muted);margin-top:4px}
.sig-tools a{color:var(--red);cursor:pointer;text-decoration:underline}
.consent{display:flex;gap:10px;align-items:flex-start;margin:16px 0;font-size:12.5px}
.consent input{margin-top:3px;transform:scale(1.3)}
button.sign{width:100%;padding:14px;background:var(--red);color:#fff;border:0;font-size:16px;font-weight:700;letter-spacing:.04em;cursor:pointer;font-family:inherit}
button.sign:hover{background:var(--red-deep)}
button.sign:disabled{background:#c9c2b6;cursor:not-allowed}
button.sign:focus-visible{outline:2px solid var(--ink);outline-offset:2px}
.err{color:var(--red-deep);font-size:13px;margin-top:8px;display:none}
.okmsg{display:none;margin-top:12px;font-size:13px}
.okmsg input{margin-top:6px}
footer{margin-top:30px;padding-top:12px;border-top:3px solid var(--ink);font-size:11px;color:var(--muted);display:flex;justify-content:space-between;gap:12px}
@media(max-width:640px){.sheet{padding:26px 18px;margin:0}.parties{grid-template-columns:1fr}h1{font-size:21px}header{flex-direction:column}.doc-meta{text-align:left}}
@media print{body{background:#fff}.sheet{box-shadow:none;margin:0;padding:24px 30px}.sign-panel{display:none}}
"""

_SIGN_JS = """
(function(){
  var panel=document.getElementById('signPanel');
  if(!panel)return;
  var token=window.location.pathname.split('/')[2];
  var canvas=document.getElementById('sigpad'),ctx=canvas.getContext('2d'),drawn=false,drawing=false;
  function fit(){var r=canvas.getBoundingClientRect();canvas.width=r.width*2;canvas.height=240;
    ctx.scale(2,2);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#1A1A1A';}
  fit();
  function pos(e){var r=canvas.getBoundingClientRect();return {x:e.clientX-r.left,y:e.clientY-r.top};}
  canvas.addEventListener('pointerdown',function(e){drawing=true;drawn=true;
    var p=pos(e);ctx.beginPath();ctx.moveTo(p.x,p.y);e.preventDefault();});
  canvas.addEventListener('pointermove',function(e){if(!drawing)return;
    var p=pos(e);ctx.lineTo(p.x,p.y);ctx.stroke();e.preventDefault();});
  ['pointerup','pointerleave'].forEach(function(ev){
    canvas.addEventListener(ev,function(){drawing=false;});});
  document.getElementById('sigClear').addEventListener('click',function(){
    ctx.setTransform(1,0,0,1,0,0);ctx.clearRect(0,0,canvas.width,canvas.height);fit();drawn=false;});
  var name=document.getElementById('signerName'),consent=document.getElementById('consent'),
      btn=document.getElementById('signBtn'),err=document.getElementById('signErr');
  function gate(){btn.disabled=!(name.value.trim().length>1&&consent.checked);}
  name.addEventListener('input',gate);consent.addEventListener('change',gate);
  btn.addEventListener('click',function(){
    btn.disabled=true;btn.textContent='Signing\\u2026';err.style.display='none';
    fetch('/api/sign/'+token,{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({signer_name:name.value.trim(),
        signer_title:document.getElementById('signerTitle').value.trim(),
        signature_image:drawn?canvas.toDataURL('image/png'):null,
        consent:consent.checked})})
    .then(function(r){return r.json().then(function(j){return {ok:r.ok,j:j};});})
    .then(function(res){
      if(res.ok){window.location.reload();}
      else{err.textContent=res.j.error||'Signing failed \\u2014 try again.';
        err.style.display='block';btn.disabled=false;btn.textContent='Sign agreement';}})
    .catch(function(){err.textContent='Network error \\u2014 try again.';
      err.style.display='block';btn.disabled=false;btn.textContent='Sign agreement';});
  });
})();
"""

_CONSOLE_JS = """
(function(){
  var createBtn=document.getElementById('createBtn');
  if(!createBtn)return;
  function v(id){return document.getElementById(id).value.trim();}
  createBtn.addEventListener('click',function(){
    var b=createBtn;b.disabled=true;
    fetch('/api/agreements/create',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({passcode:v('pc'),client_company:v('company'),
        client_name:v('cname'),client_email:v('cemail'),client_phone:v('cphone')})})
    .then(function(r){return r.json().then(function(j){return {ok:r.ok,j:j};});})
    .then(function(res){b.disabled=false;var err=document.getElementById('createErr');
      if(res.ok){err.style.display='none';
        document.getElementById('createOk').style.display='block';
        document.getElementById('linkOut').value=res.j.sign_url;}
      else{err.textContent=res.j.error||'Failed';err.style.display='block';}})
    .catch(function(){b.disabled=false;});
  });
  document.getElementById('linkOut').addEventListener('click',function(){this.select();});
  document.getElementById('listBtn').addEventListener('click',function(){
    fetch('/api/agreements/list',{method:'POST',headers:{'Content-Type':'application/json'},
      body:JSON.stringify({passcode:v('pc')})})
    .then(function(r){return r.json();})
    .then(function(j){
      var rows=(j.agreements||[]).map(function(a){
        return '<tr><td>'+a.client_company+'</td><td>'+a.client_name+'</td>'+
          '<td class="mono">'+a.status+'</td><td class="mono">'+
          (a.signed_at||a.created_at||'').slice(0,10)+'</td></tr>';}).join('');
      document.getElementById('listOut').innerHTML=
        '<table><tr><th>Company</th><th>Contact</th><th>Status</th><th>Date</th></tr>'+rows+'</table>';});
  });
})();
"""


@agreements_bp.route("/agreements/app.css", methods=["GET"])
def doc_css():
    return Response(_DOC_CSS, mimetype="text/css")


@agreements_bp.route("/agreements/sign.js", methods=["GET"])
def sign_js():
    return Response(_SIGN_JS, mimetype="application/javascript")


@agreements_bp.route("/agreements/console.js", methods=["GET"])
def console_js():
    return Response(_CONSOLE_JS, mimetype="application/javascript")


@agreements_bp.route("/agreements/logo.png", methods=["GET"])
def logo_png():
    try:
        raw = base64.b64decode(_LOGO_B64)
    except Exception:
        return Response(status=404)
    resp = Response(raw, mimetype="image/png")
    resp.headers["Cache-Control"] = "public, max-age=86400"
    return resp


# ---------------------------------------------------------------------------
# Agreement document — commercial_v1
# Mirrors the Jul 2026 commercial rate card; keep the numbers in sync with
# BULK_MARGINAL_RATES / the B2B rate card when they change.
# ---------------------------------------------------------------------------
def _doc_body(ag):
    """The agreement text with the client's details filled in."""
    effective = (ag.signed_at or ag.created_at)
    effective_str = effective.strftime("%B %d, %Y") if effective else ""
    phone = ag.client_phone or "&mdash;"
    return """
<header>
  <div>
    <img src="/agreements/logo.png" alt="Umuve" width="72">
    <h1>Commercial Services Agreement</h1>
  </div>
  <div class="doc-meta mono">DEBRIS REMOVAL &amp; CLEANOUT<br>PALM BEACH · BROWARD<br>goumuve.com · (561) 944-1636</div>
</header>

<div class="parties">
  <div>
    <div class="lbl">Provider</div>
    Umuve ("Umuve")<br>West Palm Beach, Florida<br>bookings@goumuve.com
  </div>
  <div>
    <div class="lbl">Client</div>
    Company: <b>{company}</b><br>
    Contact: <b>{name}</b><br>
    Email / phone: <b>{email}</b> · {phone}
  </div>
</div>
<p class="fine">Effective date: <b>{effective}</b></p>

<h2><span class="n">1</span>Services</h2>
<p>Umuve provides non-hazardous debris removal — post-demolition and construction debris, property cleanouts, and junk removal — at job sites the Client designates within Palm Beach and Broward counties. Work is performed by Umuve's licensed and insured operator network. Every job includes loading, hauling, lawful disposal, and before/after photo documentation.</p>

<h2><span class="n">2</span>Scheduling</h2>
<p>Umuve targets next-business-day service with two-hour arrival windows. The Client may book by phone, text, email, or through the Umuve business portal (portal.goumuve.com), where job history and invoices are available at any time.</p>

<h2><span class="n">3</span>Pricing &amp; quotes</h2>
<p>Rates follow <b>Exhibit A</b>. Each job receives a written quote (from photos or a site visit) before work begins; the quoted price is binding. If site conditions differ materially from what was quoted, Umuve will present a revised price for approval <i>before</i> proceeding — work never continues past an unapproved change.</p>
<table>
  <tr><th>Exhibit A — C&amp;D per-load rates</th><th class="num">Rate</th></tr>
  <tr><td>Quarter load</td><td class="num mono">$445</td></tr>
  <tr><td>Half load</td><td class="num mono">$795</td></tr>
  <tr><td>Three-quarter load</td><td class="num mono">$995</td></tr>
  <tr><td>Full load (disposal incl. to 2 tons)</td><td class="num mono">$1,195</td></tr>
  <tr><td>Each additional full load, same visit</td><td class="num mono">$995</td></tr>
  <tr><td>Tonnage beyond included allowance</td><td class="num mono">$85 / ton</td></tr>
</table>
<p class="fine">Dense material (concrete, dirt, tile, roofing) loads to half-bed by legal weight and is billed at the half-load rate per bed. Rates guaranteed 90 days from the effective date, then adjustable with 30 days' written notice.</p>

<h2><span class="n">4</span>Volume discount</h2>
<p>Three or more completed cleanouts in a calendar month earn a <b>10% discount on that month's invoices</b>, applied automatically.</p>

<h2><span class="n">5</span>Payment</h2>
<ul>
  <li>Payment is due on job completion by card on file or payment link.</li>
  <li>After three paid jobs, the Client may elect net-15 invoicing.</li>
  <li>Amounts 15+ days past due accrue 1.5% per month. Umuve may pause scheduling on accounts 30+ days past due.</li>
</ul>

<h2><span class="n">6</span>Excluded materials</h2>
<p>Umuve does not haul: asbestos or suspected asbestos-containing material, wet paint, solvents, chemicals, fuels, sealed or pressurized tanks, or regulated hazardous waste. <b>The Client warrants that debris presented for removal contains no such materials</b> and that any required demolition permits and abatement were the Client's responsibility and are complete.</p>

<h2><span class="n">7</span>Donation &amp; diversion</h2>
<p>Where materials are reusable, Umuve may donate them to local partner organizations rather than landfill them. Donation receipts and diversion documentation are available to the Client on request at no charge.</p>

<h2><span class="n">8</span>Insurance &amp; liability</h2>
<p>Operators carry commercial auto and general liability coverage; certificates of insurance are available on request. Property-damage claims must be reported within 48 hours of job completion. Except for gross negligence or willful misconduct, each party's total liability under this Agreement is capped at amounts paid or payable for the job giving rise to the claim.</p>

<h2><span class="n">9</span>Term &amp; electronic signature</h2>
<p>This Agreement runs month-to-month from the effective date. Either party may end it with 30 days' written notice. Jobs already scheduled are completed and paid under the terms above. This Agreement is governed by Florida law; venue is Palm Beach County. <b>The parties agree that this Agreement may be executed electronically</b> and that an electronic signature carries the same force as a handwritten one.</p>
""".format(
        company=ag.client_company,
        name=ag.client_name,
        email=ag.client_email,
        phone=phone,
        effective=effective_str,
    )


def _executed_block(ag):
    sig_img = (
        '<img src="{}" alt="signature">'.format(ag.signature_image)
        if ag.signature_image else ""
    )
    return """
<div class="executed">
  <div class="lbl">Signed electronically</div>
  {sig_img}
  <p><b>{signer}</b>{title} — on behalf of {company}</p>
  <p class="mono fine">{when} UTC · IP {ip}<br>Record SHA-256 {sha}</p>
  <p style="margin-top:8px">Accepted for Umuve by Shamar Donaldson, Founder.</p>
</div>
""".format(
        sig_img=sig_img,
        signer=ag.signer_name,
        title=", {}".format(ag.signer_title) if ag.signer_title else "",
        company=ag.client_company,
        when=ag.signed_at.strftime("%B %d, %Y %H:%M:%S") if ag.signed_at else "",
        ip=ag.signer_ip or "&mdash;",
        sha=(ag.document_sha256 or "")[:16] + "&hellip;",
    )


_SIGN_PANEL = """
<div class="sign-panel" id="signPanel">
  <h3>Sign this agreement</h3>
  <label for="signerName">Full legal name</label>
  <input type="text" id="signerName" autocomplete="name" placeholder="e.g. Marcos Rivera">
  <label for="signerTitle">Title (optional)</label>
  <input type="text" id="signerTitle" placeholder="e.g. Owner, General Contractor">
  <label>Draw your signature (optional)</label>
  <canvas id="sigpad"></canvas>
  <div class="sig-tools"><a id="sigClear">Clear signature</a></div>
  <div class="consent">
    <input type="checkbox" id="consent">
    <span>I agree to do business electronically and to sign this Agreement
    electronically. I have read the Agreement above and agree to its terms
    on behalf of the Client named in it.</span>
  </div>
  <button class="sign" id="signBtn" disabled>Sign agreement</button>
  <div class="err" id="signErr"></div>
</div>
"""


def _page(title, inner, script=None):
    script_tag = (
        '<script src="{}"></script>'.format(script) if script else ""
    )
    return (
        "<!DOCTYPE html><html lang=\"en\"><head><meta charset=\"utf-8\">"
        "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
        "<meta name=\"robots\" content=\"noindex\">"
        "<title>{title}</title>"
        "<link rel=\"stylesheet\" href=\"/agreements/app.css\"></head><body>"
        "<div class=\"sheet\">{inner}"
        "<footer><div>Umuve — Hauling made simple.</div>"
        "<div class=\"mono\">UMUVE AGREEMENTS</div></footer>"
        "</div>{script_tag}</body></html>"
    ).format(title=title, inner=inner, script_tag=script_tag)


# ---------------------------------------------------------------------------
# Public: view + sign
# ---------------------------------------------------------------------------
@agreements_bp.route("/sign/<token>", methods=["GET"])
@limiter.limit("30 per minute")
def sign_page(token):
    ag = Agreement.query.filter_by(token=token).first()
    if ag is None or ag.status == "void":
        return Response(
            _page("Agreement not found",
                  "<h1>Agreement not found</h1><p>This signing link is invalid "
                  "or has been withdrawn. Contact bookings@goumuve.com.</p>"),
            status=404, mimetype="text/html")

    if ag.status == "signed":
        # Executed copies are stored as inner content and wrapped at serve
        # time so they always load the current same-origin stylesheet.
        # (Rows written before this change stored a full document; rebuild
        # their inner from the live template — the audit fields are on the
        # row, so the rendered copy is identical.)
        inner = ag.executed_html
        if not inner or inner.lstrip().startswith("<!DOCTYPE"):
            inner = _doc_body(ag) + _executed_block(ag)
        return Response(
            _page("Umuve — Executed service agreement ({})".format(ag.client_company),
                  inner),
            mimetype="text/html")

    if ag.viewed_at is None:
        ag.viewed_at = utcnow()
        ag.status = "viewed"
        db.session.commit()

    inner = _doc_body(ag) + _SIGN_PANEL
    return Response(
        _page("Umuve — Sign your service agreement", inner,
              script="/agreements/sign.js"),
        mimetype="text/html")


@agreements_bp.route("/api/sign/<token>", methods=["POST"])
@limiter.limit("10 per minute")
def sign_submit(token):
    ag = Agreement.query.filter_by(token=token).first()
    if ag is None or ag.status == "void":
        return jsonify({"error": "Agreement not found"}), 404
    if ag.status == "signed":
        return jsonify({"error": "This agreement has already been signed."}), 409

    data = request.get_json() or {}
    signer_name = (data.get("signer_name") or "").strip()
    if len(signer_name) < 2:
        return jsonify({"error": "Full legal name is required."}), 400
    if not data.get("consent"):
        return jsonify({"error": "You must agree to sign electronically."}), 400

    sig_img = data.get("signature_image")
    if sig_img and not str(sig_img).startswith("data:image/png;base64,"):
        sig_img = None  # only accept the canvas PNG format we generate

    ag.signer_name = signer_name[:120]
    ag.signer_title = (data.get("signer_title") or "").strip()[:120] or None
    ag.signature_image = sig_img
    ag.signer_ip = _client_ip()[:64]
    ag.signer_user_agent = (request.headers.get("User-Agent") or "")[:255]
    ag.signed_at = utcnow()
    ag.status = "signed"

    ag.document_sha256 = hashlib.sha256(
        (_doc_body(ag) + "|" + ag.signer_name + "|" + ag.signed_at.isoformat())
        .encode("utf-8")).hexdigest()
    # Immutable inner snapshot (page shell + stylesheet applied at serve time).
    ag.executed_html = _doc_body(ag) + _executed_block(ag)
    db.session.commit()

    # Notify both parties — best-effort, never blocks the signature.
    base = os.environ.get("PUBLIC_BASE_URL", "https://junkos-backend.onrender.com")
    view_url = "{}/sign/{}".format(base.rstrip("/"), ag.token)
    try:
        from email_service import send_email
        notice = (
            '<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;'
            'max-width:560px;margin:0 auto;padding:32px 24px">'
            '<p><img src="https://goumuve.com/logo-full.png" alt="Umuve" width="120"></p>'
            '<h2 style="color:#111">Agreement signed</h2>'
            '<p style="color:#444;line-height:1.6"><b>{signer}</b> signed the Umuve '
            'commercial services agreement for <b>{company}</b> on {when} UTC.</p>'
            '<p style="margin:24px 0"><a href="{url}" style="background:#C52222;'
            'color:#fff;padding:13px 26px;text-decoration:none;font-weight:700">'
            'View the executed agreement</a></p>'
            '<p style="color:#888;font-size:13px">This link permanently serves the '
            'executed copy. Keep this email for your records.</p></div>'
        ).format(signer=ag.signer_name, company=ag.client_company,
                 when=ag.signed_at.strftime("%B %d, %Y %H:%M"), url=view_url)
        send_email(to_email=ag.client_email,
                   subject="Executed: Umuve service agreement — {}".format(ag.client_company),
                   html_content=notice)
        send_email(to_email=SEVS_NOTIFY_EMAIL,
                   subject="SIGNED: {} ({})".format(ag.client_company, ag.signer_name),
                   html_content=notice)
    except Exception:
        logger.exception("agreement %s: executed-copy email failed", ag.id)

    return jsonify({"success": True, "status": "signed"}), 200


# ---------------------------------------------------------------------------
# Console (passcode-gated, same code as the VA tool suite)
# ---------------------------------------------------------------------------
_CONSOLE_HTML = """
<header>
  <div><img src="/agreements/logo.png" alt="Umuve" width="72"><h1>Agreements</h1></div>
  <div class="doc-meta mono">SEND · TRACK · SIGNED COPIES</div>
</header>
<div class="sign-panel">
  <h3>New agreement</h3>
  <label for="pc">Access code</label><input type="text" id="pc" autocomplete="off">
  <label for="company">Company</label><input type="text" id="company" placeholder="e.g. Rivera Demolition LLC">
  <label for="cname">Contact name</label><input type="text" id="cname" placeholder="e.g. Marcos Rivera">
  <label for="cemail">Email</label><input type="text" id="cemail" placeholder="who receives the signing link">
  <label for="cphone">Phone (optional)</label><input type="text" id="cphone">
  <button class="sign" id="createBtn" style="margin-top:16px">Create &amp; email signing link</button>
  <div class="err" id="createErr"></div>
  <div class="okmsg" id="createOk">
    <b>Link created and emailed.</b> Text it too:<br>
    <input type="text" id="linkOut" readonly>
  </div>
</div>
<div class="sign-panel">
  <h3>Recent</h3>
  <button class="sign" id="listBtn">Load recent agreements</button>
  <div id="listOut" style="margin-top:10px"></div>
</div>
"""


@agreements_bp.route("/agreements", methods=["GET"])
def console_page():
    return Response(
        _page("Umuve — Agreements", _CONSOLE_HTML,
              script="/agreements/console.js"),
        mimetype="text/html")


@agreements_bp.route("/api/agreements/create", methods=["POST"])
@limiter.limit("10 per minute")
def create_agreement():
    data = request.get_json() or {}
    if not _passcode_ok(data.get("passcode")):
        return jsonify({"error": "Invalid access code"}), 403

    company = (data.get("client_company") or "").strip()
    name = (data.get("client_name") or "").strip()
    email = (data.get("client_email") or "").strip()
    if not company or not name or "@" not in email:
        return jsonify({"error": "Company, contact name, and a valid email are required."}), 400

    ag = Agreement(
        token=secrets.token_urlsafe(24),
        client_company=company[:200],
        client_name=name[:120],
        client_email=email[:255],
        client_phone=(data.get("client_phone") or "").strip()[:40] or None,
    )
    db.session.add(ag)
    db.session.commit()

    base = os.environ.get("PUBLIC_BASE_URL", "https://junkos-backend.onrender.com")
    sign_url = "{}/sign/{}".format(base.rstrip("/"), ag.token)

    try:
        from email_service import send_email
        send_email(
            to_email=ag.client_email,
            subject="Your Umuve service agreement is ready to sign",
            html_content=(
                '<div style="font-family:-apple-system,BlinkMacSystemFont,sans-serif;'
                'max-width:560px;margin:0 auto;padding:32px 24px">'
                '<p><img src="https://goumuve.com/logo-full.png" alt="Umuve" width="120"></p>'
                '<h2 style="color:#111">Hi {name},</h2>'
                '<p style="color:#444;line-height:1.6">Your Umuve commercial services '
                'agreement for <b>{company}</b> is ready. It takes about two minutes to '
                'review and sign — rates, terms, and everything we discussed are in it.</p>'
                '<p style="margin:24px 0"><a href="{url}" style="background:#C52222;'
                'color:#fff;padding:13px 26px;text-decoration:none;font-weight:700">'
                'Review &amp; sign</a></p>'
                '<p style="color:#888;font-size:13px">Questions? Just reply to this '
                'email or call (561) 944-1636.</p></div>'
            ).format(name=ag.client_name, company=ag.client_company, url=sign_url),
        )
    except Exception:
        logger.exception("agreement %s: signing-link email failed", ag.id)

    return jsonify({"success": True, "sign_url": sign_url,
                    "agreement": ag.to_dict()}), 201


@agreements_bp.route("/api/agreements/list", methods=["POST"])
@limiter.limit("20 per minute")
def list_agreements():
    data = request.get_json() or {}
    if not _passcode_ok(data.get("passcode")):
        return jsonify({"error": "Invalid access code"}), 403
    rows = (Agreement.query.order_by(Agreement.created_at.desc())
            .limit(50).all())
    return jsonify({"agreements": [a.to_dict() for a in rows]}), 200
