"""
B2B Commercial Portal — Stripe billing (Spec 04 §8).

BILLING OWNERSHIP (audit F24 — one owner per charge, never two)
================================================================
Two systems can bill an org, and they must never both charge the base fee for
the same period:

  * **Stripe Subscription** (``subscribe_org`` / ``create_checkout_session``,
    ``org.stripe_subscription_id`` set): Stripe charges the tier's monthly
    base automatically. It OWNS the base fee. Contract invoices generated by
    ``portal_invoicing`` for such an org carry usage/overage lines only.
  * **Contract invoice** (``portal_invoicing.generate_monthly_invoices``, org
    has an active ``Contract`` but NO Stripe subscription — e.g. enterprise
    net-30, invoiced): the monthly invoice OWNS the base fee and adds one
    ``kind='base_fee'`` line.

``base_fee_owner(org)`` is the single decision point and
``claim_base_fee(org_id, period, kind)`` is the idempotency lock: it inserts an
``AutomationEvent`` keyed ``(portal_base_fee, org_period, "<org_id>:<YYYY-MM>")``
so a second attempt (any path, any run) to bill the base fee for the same
period fails the unique constraint and is skipped.

Included pickups are always covered by whoever owns the base fee; overage
pickups are always billed on the contract invoice.

Responsibilities of this module:
  1. Bootstrap the catalog: create Product + Price rows for Starter/Pro/
     Enterprise tiers in Stripe (or report the existing IDs). Idempotent —
     we look up by name before creating. Price IDs land in
     `portal_billing_config.json` so the app can subscribe orgs without
     hitting the Stripe API every time.
  2. Subscribe an org: find-or-create the Stripe customer, attach a
     subscription at the chosen tier, and store the resulting IDs on Org.
  3. Deliver contract invoices to Stripe (``push_portal_invoice_to_stripe``):
     draft first, line items attached explicitly to that draft, every Stripe
     id persisted, idempotency keys derived from (org_id, period) so retries
     are safe.

Usage:
    STRIPE_API_KEY=sk_test_... python billing_portal.py bootstrap
    STRIPE_API_KEY=sk_test_... python billing_portal.py subscribe <org_id> <tier>

The webhook handler is registered under /portal/v1/billing/webhook — it only
cares about checkout.session.completed, invoice.paid, invoice.payment_failed,
and customer.subscription.updated (to sync tier + status). It fails closed in
production when STRIPE_WEBHOOK_SECRET_PORTAL is unset (see webhook_guard).
"""

import json
import logging
import os
import sys
from datetime import datetime
from functools import wraps
from pathlib import Path

from flask import Blueprint, jsonify, request

logger = logging.getLogger(__name__)

# Portal tier catalog — spec §8.
TIERS = {
    "starter": {
        "name": "Umuve Portal — Starter",
        "description": "1 property, 3 users, 10 pickups incl, $65/overage",
        "monthly_cents": 49900,
        "overage_cents": 6500,
    },
    "pro": {
        "name": "Umuve Portal — Pro",
        "description": "Up to 25 properties, 15 users, 60 pickups incl, $55/overage",
        "monthly_cents": 199900,
        "overage_cents": 5500,
    },
    "enterprise": {
        "name": "Umuve Portal — Enterprise",
        "description": "Unlimited properties/users, 150 pickups incl, $45/overage, net-30",
        "monthly_cents": 499900,
        "overage_cents": 4500,
    },
}

CONFIG_PATH = Path(
    os.environ.get(
        "PORTAL_BILLING_CONFIG",
        os.path.join(os.path.dirname(__file__), "portal_billing_config.json"),
    )
)


# ---------------------------------------------------------------------------
# Config persistence — small JSON file; product/price IDs are public-safe
# ---------------------------------------------------------------------------
def _load_config():
    if CONFIG_PATH.exists():
        try:
            return json.loads(CONFIG_PATH.read_text())
        except Exception:
            return {}
    return {}


def _save_config(cfg):
    try:
        CONFIG_PATH.write_text(json.dumps(cfg, indent=2))
    except Exception:
        # On read-only / ephemeral filesystems the cache write can fail; that's
        # fine — resolve_tier_price_id() rediscovers from Stripe when needed.
        logger.warning("could not persist portal billing config to %s", CONFIG_PATH)


def _stripe_key(override=None):
    """Stripe secret key. Prefer STRIPE_SECRET_KEY (used by the rest of the
    backend); fall back to the legacy STRIPE_API_KEY name."""
    return override or os.environ.get("STRIPE_SECRET_KEY") or os.environ.get("STRIPE_API_KEY", "")


def _stripe_client(override=None):
    """Return the configured ``stripe`` module (api_key set) or None when no
    key is configured / SDK missing. Tests patch this to inject a fake."""
    key = _stripe_key(override)
    if not key:
        return None
    try:
        import stripe
    except ImportError:
        return None
    stripe.api_key = key
    return stripe


def period_key(period_start):
    """'YYYY-MM' key for a billing period (idempotency + Stripe keys)."""
    return "{:04d}-{:02d}".format(period_start.year, period_start.month)


def base_fee_owner(org):
    """'subscription' when Stripe charges the tier base automatically,
    'contract_invoice' when the monthly contract invoice must carry it."""
    if org is not None and getattr(org, "stripe_subscription_id", None):
        return "subscription"
    return "contract_invoice"


def claim_base_fee(org_id, period_start, kind):
    """Idempotency lock for billing the base fee once per (org, period).

    Inserts an AutomationEvent (unique on kind/subject) inside a savepoint.
    Returns True if THIS caller now owns the base fee for the period, False
    if it was already billed (by any path). Does not commit — the caller's
    transaction decides.
    """
    from sqlalchemy.exc import IntegrityError
    from models import db, AutomationEvent
    subject = "{}:{}".format(org_id, period_key(period_start))
    try:
        with db.session.begin_nested():
            db.session.add(AutomationEvent(
                kind="portal_base_fee", subject_type="org_period",
                subject_id=subject, detail=kind,
            ))
        return True
    except IntegrityError:
        return False


def base_fee_already_billed(org_id, period_start):
    from models import db, AutomationEvent
    subject = "{}:{}".format(org_id, period_key(period_start))
    return db.session.query(AutomationEvent.id).filter_by(
        kind="portal_base_fee", subject_type="org_period", subject_id=subject,
    ).first() is not None


def resolve_tier_price_id(tier):
    """Return the Stripe monthly price id for a tier.

    Prefers the cached config file, but if it's missing (Render's filesystem is
    ephemeral across redeploys / multi-instance), rediscovers the price from
    Stripe by product name + amount — the same way bootstrap() does — so
    checkout/subscribe don't break with "run bootstrap first" after a redeploy.
    Only raises if the product/price genuinely isn't in Stripe yet.
    """
    if tier not in TIERS:
        raise ValueError("invalid tier {}".format(tier))
    pid = _load_config().get("tiers", {}).get(tier, {}).get("base_price_id")
    if pid:
        return pid

    import stripe
    key = _stripe_key()
    if not key:
        raise RuntimeError("Stripe key not set")
    stripe.api_key = key
    meta = TIERS[tier]
    product = next(
        (p for p in stripe.Product.list(limit=100).auto_paging_iter()
         if p.name == meta["name"]),
        None,
    )
    if not product:
        raise RuntimeError("tier {} not bootstrapped in Stripe — run bootstrap".format(tier))
    price = next(
        (pr for pr in stripe.Price.list(product=product.id, limit=10).auto_paging_iter()
         if pr.unit_amount == meta["monthly_cents"]
         and pr.recurring and pr.recurring.interval == "month"),
        None,
    )
    if not price:
        raise RuntimeError("no monthly price for tier {} in Stripe".format(tier))
    # Best-effort re-cache so subsequent calls skip the lookup.
    cfg = _load_config()
    cfg.setdefault("tiers", {}).setdefault(tier, {}).update(
        {"product_id": product.id, "base_price_id": price.id}
    )
    _save_config(cfg)
    return price.id


# ---------------------------------------------------------------------------
# Bootstrap: create products + prices in Stripe (idempotent)
# ---------------------------------------------------------------------------
def bootstrap(stripe_api_key=None):
    """Create or reuse Stripe products + prices for all tiers. Returns the
    full config dict. Requires stripe SDK; skips if not installed."""
    try:
        import stripe
    except ImportError:
        raise SystemExit(
            "stripe SDK not installed. Run: pip install stripe"
        )

    stripe.api_key = _stripe_key(stripe_api_key)
    if not stripe.api_key:
        raise SystemExit("Stripe key not set (STRIPE_SECRET_KEY)")

    cfg = _load_config()
    cfg.setdefault("tiers", {})

    for tier, meta in TIERS.items():
        existing = cfg["tiers"].get(tier, {})
        product_id = existing.get("product_id")
        base_price_id = existing.get("base_price_id")

        if not product_id:
            products = stripe.Product.list(limit=100)
            match = next(
                (p for p in products.auto_paging_iter() if p.name == meta["name"]),
                None,
            )
            if match:
                product_id = match.id
            else:
                p = stripe.Product.create(
                    name=meta["name"],
                    description=meta["description"],
                    metadata={"tier": tier, "source": "portal_bootstrap"},
                )
                product_id = p.id

        if not base_price_id:
            prices = stripe.Price.list(product=product_id, limit=10)
            match = next(
                (
                    pr
                    for pr in prices.auto_paging_iter()
                    if pr.unit_amount == meta["monthly_cents"]
                    and pr.recurring
                    and pr.recurring.interval == "month"
                ),
                None,
            )
            if match:
                base_price_id = match.id
            else:
                pr = stripe.Price.create(
                    product=product_id,
                    unit_amount=meta["monthly_cents"],
                    currency="usd",
                    recurring={"interval": "month"},
                    nickname="{} Monthly".format(tier),
                )
                base_price_id = pr.id

        cfg["tiers"][tier] = {
            "product_id": product_id,
            "base_price_id": base_price_id,
            "monthly_cents": meta["monthly_cents"],
            "overage_cents": meta["overage_cents"],
        }

    cfg["bootstrapped_at"] = datetime.utcnow().isoformat()
    _save_config(cfg)
    return cfg


# ---------------------------------------------------------------------------
# Subscribe: find-or-create customer + subscription for an org
# ---------------------------------------------------------------------------
def subscribe_org(org_id, tier=None, stripe_api_key=None):
    """Create a Stripe Customer + Subscription for an org. Idempotent: if
    the org already has a stripe_subscription_id we reuse it."""
    try:
        import stripe
    except ImportError:
        raise SystemExit("stripe SDK not installed")

    from models import db, Org

    stripe.api_key = _stripe_key(stripe_api_key)
    if not stripe.api_key:
        raise SystemExit("Stripe key not set (STRIPE_SECRET_KEY)")

    org = db.session.get(Org, org_id)
    if not org:
        raise SystemExit("org {} not found".format(org_id))
    tier = tier or org.tier
    if tier not in TIERS:
        raise SystemExit("invalid tier {}".format(tier))

    # Resilient: uses the cached config if present, else rediscovers from Stripe.
    price_id = resolve_tier_price_id(tier)

    if not org.stripe_customer_id:
        customer = stripe.Customer.create(
            email=org.billing_email,
            name=org.name,
            metadata={"org_id": org.id, "source": "portal"},
        )
        org.stripe_customer_id = customer.id

    if org.stripe_subscription_id:
        sub = stripe.Subscription.retrieve(org.stripe_subscription_id)
    else:
        sub = stripe.Subscription.create(
            customer=org.stripe_customer_id,
            items=[{"price": price_id}],
            collection_method="send_invoice"
            if tier == "enterprise"
            else "charge_automatically",
            days_until_due=30 if tier == "enterprise" else None,
            metadata={"org_id": org.id, "tier": tier},
        )
        org.stripe_subscription_id = sub.id

    org.tier = tier
    org.status = "active"
    db.session.commit()
    return {"customer_id": org.stripe_customer_id, "subscription_id": sub.id}


# ---------------------------------------------------------------------------
# Flask webhook blueprint: /portal/v1/billing/webhook
# ---------------------------------------------------------------------------
def push_portal_invoice_to_stripe(org, portal_invoice, line_items=None):
    """Deliver a PortalInvoice to Stripe. Retryable and idempotent.

    Order of operations (audit F24):
      1. Create the Stripe invoice DRAFT first (idempotency key
         ``portal-inv-<org>-<period>-create``) and persist its id immediately.
      2. Create one InvoiceItem per non-zero line, attached explicitly with
         ``invoice=<draft id>`` (never a floating pending item), each with its
         own stable key; persist ``stripe_invoice_item_id`` on the line.
      3. Finalize (key ``...-finalize``) and stamp ``sent_at``.

    A retry after a partial failure resumes from the persisted ids: an
    existing draft gets its missing lines attached and is finalized; an
    already-open/paid Stripe invoice just gets ``sent_at`` stamped.

    Returns the Stripe invoice id on success, None when it cannot deliver yet
    (no Stripe customer, no API key, zero total, or a Stripe error — recorded
    on ``delivery_error`` so the next run retries). Never raises. Does not
    commit; the caller owns the transaction.
    """
    if not org or not getattr(org, "stripe_customer_id", None):
        return None
    if (portal_invoice.total_cents or 0) <= 0:
        return None
    stripe = _stripe_client()
    if stripe is None:
        return None

    if line_items is None:
        line_items = list(portal_invoice.line_items or [])
    period = period_key(portal_invoice.period_start)
    key_base = "portal-inv-{}-{}".format(org.id, period)

    portal_invoice.delivery_attempts = (portal_invoice.delivery_attempts or 0) + 1
    portal_invoice.last_delivery_attempt_at = datetime.utcnow()
    try:
        # 1. Draft (or resume the persisted one).
        inv = None
        if portal_invoice.stripe_invoice_id:
            inv = stripe.Invoice.retrieve(portal_invoice.stripe_invoice_id)
            if getattr(inv, "status", None) in ("open", "paid", "uncollectible"):
                portal_invoice.sent_at = portal_invoice.sent_at or datetime.utcnow()
                portal_invoice.delivery_error = None
                return inv.id
            if getattr(inv, "status", None) == "void":
                inv = None  # voided in Stripe — issue a fresh one
        if inv is None:
            inv = stripe.Invoice.create(
                customer=org.stripe_customer_id,
                collection_method="send_invoice",
                days_until_due=int(getattr(org, "net_terms_days", None) or 30),
                auto_advance=False,
                metadata={
                    "portal_invoice_id": portal_invoice.id,
                    "number": portal_invoice.number,
                    "org_id": org.id,
                    "period": period,
                },
                idempotency_key=key_base + "-create",
            )
            portal_invoice.stripe_invoice_id = inv.id

        # 2. Lines, attached explicitly to the draft.
        for n, li in enumerate(line_items):
            amt = int(li.amount_cents or 0)
            if amt <= 0 or getattr(li, "stripe_invoice_item_id", None):
                continue
            item = stripe.InvoiceItem.create(
                customer=org.stripe_customer_id,
                invoice=inv.id,
                amount=amt,
                currency="usd",
                description=(li.description or "Pickup")[:200],
                metadata={"portal_invoice_id": portal_invoice.id,
                          "line_kind": getattr(li, "kind", None) or ""},
                idempotency_key="{}-line-{}".format(key_base, n),
            )
            li.stripe_invoice_item_id = item.id

        # 3. Finalize so it's issued (and emailed for send_invoice).
        stripe.Invoice.finalize_invoice(inv.id, idempotency_key=key_base + "-finalize")
        portal_invoice.sent_at = datetime.utcnow()
        portal_invoice.delivery_error = None
        return inv.id
    except Exception as exc:
        logger.exception(
            "push_portal_invoice_to_stripe failed for org=%s invoice=%s",
            getattr(org, "id", "?"), getattr(portal_invoice, "id", "?"),
        )
        portal_invoice.delivery_error = str(exc)[:500]
        return None


def create_checkout_session(org, tier, success_url, cancel_url):
    """Stripe Checkout (subscription mode) — collects a card AND starts the
    org's subscription in one hosted flow. Returns the Checkout URL. The
    checkout.session.completed webhook captures customer+subscription onto the
    org and flips it active. This is the self-serve path (vs. subscribe_org,
    which creates a subscription with no payment method)."""
    if tier not in TIERS:
        raise ValueError("invalid tier {}".format(tier))
    import stripe
    key = _stripe_key()
    if not key:
        raise RuntimeError("Stripe key not set (STRIPE_SECRET_KEY)")
    stripe.api_key = key
    # Resilient price lookup (cache or Stripe discovery) — survives a lost config.
    price_id = resolve_tier_price_id(tier)
    params = {
        "mode": "subscription",
        "line_items": [{"price": price_id, "quantity": 1}],
        "success_url": success_url,
        "cancel_url": cancel_url,
        "metadata": {"org_id": org.id, "tier": tier},
        "subscription_data": {"metadata": {"org_id": org.id, "tier": tier}},
        "allow_promotion_codes": True,
    }
    if org.stripe_customer_id:
        params["customer"] = org.stripe_customer_id
    elif org.billing_email:
        params["customer_email"] = org.billing_email
    return stripe.checkout.Session.create(**params).url


def create_billing_portal_session(org, return_url):
    """Stripe Customer Portal link so an org can manage its card, subscription,
    and invoices. Requires an existing Stripe customer."""
    if not org or not org.stripe_customer_id:
        raise RuntimeError("org has no Stripe customer yet")
    import stripe
    key = os.environ.get("STRIPE_SECRET_KEY")
    if not key:
        raise RuntimeError("STRIPE_SECRET_KEY not set")
    stripe.api_key = key
    return stripe.billing_portal.Session.create(
        customer=org.stripe_customer_id, return_url=return_url
    ).url


billing_portal_bp = Blueprint(
    "billing_portal", __name__, url_prefix="/portal/v1/billing"
)


def _require_admin(f):
    """Admin-only guard (mirrors routes/admin.py)."""
    @wraps(f)
    def wrapper(*args, **kwargs):
        from auth_routes import require_auth
        from models import db, User

        @require_auth
        def inner(user_id, *a, **kw):
            user = db.session.get(User, user_id)
            if not user or user.role != "admin":
                return jsonify({"error": "Admin access required"}), 403
            return f(user_id=user_id, *a, **kw)

        return inner(*args, **kwargs)
    return wrapper


@billing_portal_bp.route("/bootstrap", methods=["POST"])
@_require_admin
def bootstrap_route(user_id):
    """Admin-triggered: create/verify Stripe tier products + prices.

    Idempotent — reuses existing IDs and just reports them on re-run. Returns
    the resulting tier->price config so you can confirm it in one call instead
    of shelling into the server. Requires STRIPE_SECRET_KEY on the server.
    """
    try:
        cfg = bootstrap()
        return jsonify({"success": True, "config": cfg}), 200
    except Exception as e:
        logging.getLogger(__name__).exception("billing bootstrap failed")
        return jsonify({"success": False, "error": str(e)}), 502


@billing_portal_bp.route("/status", methods=["GET"])
@_require_admin
def billing_status(user_id):
    """Activation readiness for B2B billing — no writes. Reports whether Stripe
    is keyed, each tier is bootstrapped (price resolvable), and the webhook
    secret is set, plus a live org status breakdown. One call to see exactly
    what's left before billing is GO."""
    from models import db, Org

    checks = []

    def add(name, status, detail):
        checks.append({"check": name, "status": status, "detail": detail})

    keyed = bool(_stripe_key())
    add("stripe_key", "pass" if keyed else "fail",
        "STRIPE_SECRET_KEY {}".format("set" if keyed else "missing — billing can't run"))

    tier_state = {}
    all_boot = True
    for tier in TIERS:
        try:
            pid = resolve_tier_price_id(tier)
            tier_state[tier] = {"bootstrapped": True, "price_id": pid}
        except Exception as e:
            tier_state[tier] = {"bootstrapped": False, "error": str(e)[:120]}
            all_boot = False
    add("tiers_bootstrapped", "pass" if all_boot else ("fail" if keyed else "warn"),
        "{} / {} tiers have a Stripe price".format(
            sum(1 for t in tier_state.values() if t.get("bootstrapped")), len(TIERS)))

    wh = bool(os.environ.get("STRIPE_WEBHOOK_SECRET_PORTAL"))
    add("webhook_secret", "pass" if wh else "warn",
        "STRIPE_WEBHOOK_SECRET_PORTAL {}".format(
            "set" if wh else "missing — subscription/invoice status won't sync back"))

    counts = {}
    try:
        for st, n in db.session.query(Org.status, db.func.count(Org.id)).group_by(Org.status).all():
            counts[st or "none"] = n
    except Exception:
        pass

    blocking = (not keyed) or (not all_boot)
    verdict = "NO-GO" if blocking else ("ALMOST" if not wh else "GO")
    summary = {
        "GO": "Billing is live — orgs can subscribe and status syncs back.",
        "ALMOST": "Orgs can subscribe; set STRIPE_WEBHOOK_SECRET_PORTAL so paid/past-due syncs.",
        "NO-GO": "Run bootstrap (POST /portal/v1/billing/bootstrap) and set STRIPE_SECRET_KEY.",
    }[verdict]

    return jsonify({
        "verdict": verdict,
        "summary": summary,
        "checks": checks,
        "tiers": tier_state,
        "org_status_counts": counts,
        "webhook_url": (os.environ.get("PUBLIC_BASE_URL", "https://junkos-backend.onrender.com").rstrip("/")
                        + "/portal/v1/billing/webhook"),
    }), 200


@billing_portal_bp.route("/register-webhook", methods=["POST"])
@_require_admin
def register_webhook(user_id):
    """Create the portal billing webhook in Stripe via the API (no dashboard
    clicking) and return its signing secret so you can set
    STRIPE_WEBHOOK_SECRET_PORTAL. The secret is ONLY returned by Stripe at
    creation time. Idempotent-ish: if an endpoint for this URL already exists,
    pass ?recreate=1 to delete + recreate it and get a fresh secret.
    """
    try:
        import stripe
    except ImportError:
        return jsonify({"success": False, "error": "stripe SDK unavailable"}), 503

    key = _stripe_key()
    if not key:
        return jsonify({"success": False, "error": "STRIPE_SECRET_KEY not set"}), 400
    stripe.api_key = key

    base = os.environ.get("PUBLIC_BASE_URL", "https://junkos-backend.onrender.com").rstrip("/")
    url = base + "/portal/v1/billing/webhook"
    events = [
        "checkout.session.completed",
        "customer.subscription.updated",
        "invoice.paid",
        "invoice.payment_failed",
    ]
    recreate = (request.args.get("recreate") or "").lower() in ("1", "true", "yes")

    try:
        existing = next(
            (e for e in stripe.WebhookEndpoint.list(limit=100).auto_paging_iter() if e.url == url),
            None,
        )
        if existing and not recreate:
            return jsonify({
                "success": True,
                "already_exists": True,
                "endpoint_id": existing.id,
                "note": ("A webhook for this URL already exists. Stripe only reveals the "
                         "signing secret at creation, so to get a fresh one call this again "
                         "with ?recreate=1 (deletes + recreates), or roll the secret in the "
                         "Stripe dashboard."),
            }), 200
        if existing and recreate:
            stripe.WebhookEndpoint.delete(existing.id)

        ep = stripe.WebhookEndpoint.create(
            url=url, enabled_events=events, description="Umuve portal billing",
        )
        return jsonify({
            "success": True,
            "endpoint_id": ep.id,
            "url": url,
            "events": events,
            "signing_secret": ep.secret,
            "next_step": ("Set STRIPE_WEBHOOK_SECRET_PORTAL = the signing_secret above on "
                          "Render (junkos-backend → Environment). Do NOT paste it in chat."),
        }), 200
    except Exception as e:
        logging.getLogger(__name__).exception("register-webhook failed")
        return jsonify({"success": False, "error": str(e)[:200]}), 502


@billing_portal_bp.route("/contracts", methods=["POST"])
@_require_admin
def create_contract_route(user_id):
    """Admin: put a Contract on file for an org so recurring pickups can be
    priced (portal_recurring refuses to generate $0 jobs without one).

    Body: {org_id, tier?, monthly_base_cents?, metered_per_pickup_cents?,
           included_pickups?, effective_from? (ISO), effective_to? (ISO)}
    Defaults come from the TIERS catalog for the org's tier. Any currently
    open contract for the org is closed (effective_to = now) first.
    """
    from models import db, Org, Contract, active_contract_for_org

    data = request.get_json(silent=True) or {}
    org = db.session.get(Org, data.get("org_id") or "")
    if not org:
        return jsonify({"success": False, "error": "org not found"}), 404
    tier = data.get("tier") or org.tier
    if tier not in TIERS:
        return jsonify({"success": False, "error": "invalid tier"}), 400
    catalog = TIERS[tier]

    def _int(name, default):
        try:
            return int(data.get(name, default))
        except (TypeError, ValueError):
            return default

    def _dt(name):
        raw = data.get(name)
        if not raw:
            return None
        try:
            return datetime.fromisoformat(str(raw).replace("Z", "+00:00")).replace(tzinfo=None)
        except ValueError:
            return None

    now = datetime.utcnow()
    current = active_contract_for_org(org.id, now)
    if current is not None:
        current.effective_to = now
    contract = Contract(
        org_id=org.id,
        tier=tier,
        monthly_base_cents=_int("monthly_base_cents", catalog["monthly_cents"]),
        metered_per_pickup_cents=_int("metered_per_pickup_cents", catalog["overage_cents"]),
        included_pickups=_int("included_pickups", 0),
        effective_from=_dt("effective_from") or now,
        effective_to=_dt("effective_to"),
    )
    db.session.add(contract)
    db.session.commit()
    return jsonify({
        "success": True,
        "contract": {
            "id": contract.id, "org_id": org.id, "tier": tier,
            "monthly_base_cents": contract.monthly_base_cents,
            "metered_per_pickup_cents": contract.metered_per_pickup_cents,
            "included_pickups": contract.included_pickups,
            "effective_from": contract.effective_from.isoformat(),
            "effective_to": contract.effective_to.isoformat() if contract.effective_to else None,
            "base_fee_owner": base_fee_owner(org),
        },
    }), 201


@billing_portal_bp.route("/webhook", methods=["POST"])
def stripe_webhook():
    """Handle Stripe events relevant to portal subscriptions."""
    try:
        import stripe
    except ImportError:
        return jsonify({"error": "stripe unavailable"}), 503

    from models import db, Org, PortalInvoice

    from webhook_guard import allow_when_secret_missing, record_provider_event

    payload = request.data
    sig = request.headers.get("Stripe-Signature", "")
    secret = os.environ.get("STRIPE_WEBHOOK_SECRET_PORTAL", "")
    if not secret and not allow_when_secret_missing(
        "portal_stripe", "Org activation and invoice paid/failed sync are paused.",
    ):
        return jsonify({"error": "webhook_secret_not_configured"}), 401
    try:
        if secret:
            event = stripe.Webhook.construct_event(payload, sig, secret)
        else:
            event = json.loads(payload.decode("utf-8"))
    except Exception as exc:
        logger.warning("portal stripe webhook rejected: %s", exc)
        return jsonify({"error": "invalid_signature"}), 400

    etype = event["type"] if isinstance(event, dict) else event.type
    event_id = event.get("id") if isinstance(event, dict) else getattr(event, "id", None)
    # Stripe retries until it sees a 2xx; the event id is stable across retries.
    if event_id and not record_provider_event("stripe_portal", event_id, event_type=etype):
        return jsonify({"ok": True, "duplicate": True})
    data = (
        event["data"]["object"]
        if isinstance(event, dict)
        else event.data.object
    )

    if etype == "checkout.session.completed":
        # Self-serve subscribe finished — capture the Stripe customer +
        # subscription onto the org and activate it.
        meta = (data.get("metadata") if isinstance(data, dict) else data.metadata) or {}
        org_id = meta.get("org_id")
        org = db.session.get(Org, org_id) if org_id else None
        if org:
            cust = data.get("customer") if isinstance(data, dict) else data.customer
            sub = data.get("subscription") if isinstance(data, dict) else data.subscription
            if cust:
                org.stripe_customer_id = cust
            if sub:
                org.stripe_subscription_id = sub
            if meta.get("tier"):
                org.tier = meta["tier"]
            org.status = "active"
            db.session.commit()

    elif etype == "customer.subscription.updated":
        sub_id = data.get("id") if isinstance(data, dict) else data.id
        status = data.get("status") if isinstance(data, dict) else data.status
        org = (
            db.session.query(Org).filter_by(stripe_subscription_id=sub_id).first()
        )
        if org:
            mapping = {
                "active": "active",
                "past_due": "past_due",
                "canceled": "churned",
                "unpaid": "past_due",
                "paused": "paused",
                "trialing": "trial",
            }
            org.status = mapping.get(status, org.status)
            db.session.commit()

    elif etype == "invoice.paid":
        stripe_invoice_id = (
            data.get("id") if isinstance(data, dict) else data.id
        )
        inv = (
            db.session.query(PortalInvoice)
            .filter_by(stripe_invoice_id=stripe_invoice_id)
            .first()
        )
        if inv:
            inv.status = "paid"
            inv.paid_at = datetime.utcnow()
            db.session.commit()

    elif etype == "invoice.payment_failed":
        stripe_invoice_id = (
            data.get("id") if isinstance(data, dict) else data.id
        )
        inv = (
            db.session.query(PortalInvoice)
            .filter_by(stripe_invoice_id=stripe_invoice_id)
            .first()
        )
        if inv:
            inv.status = "past_due"
            org = db.session.get(Org, inv.org_id)
            if org:
                org.status = "past_due"  # holds recurring job-gen (Stage 5)
            db.session.commit()
            # Dunning: tell the org payment failed + how to fix it. Never raises.
            try:
                if org and org.billing_email:
                    from notifications import send_email
                    from email_templates import b2b_dunning_html
                    manage_url = os.environ.get("PORTAL_URL", "https://portal.goumuve.com") + "/settings"
                    send_email(
                        org.billing_email,
                        "Action needed: your Umuve payment failed",
                        b2b_dunning_html(org.name, inv.number,
                                         (inv.total_cents or 0) / 100.0, manage_url),
                    )
            except Exception:
                logger.exception("dunning email failed for org=%s", getattr(org, "id", "?"))

    return jsonify({"ok": True})


# ---------------------------------------------------------------------------
# CLI entrypoint
# ---------------------------------------------------------------------------
def main():
    argv = sys.argv[1:]
    if not argv or argv[0] in ("-h", "--help"):
        print(__doc__)
        return
    if argv[0] == "bootstrap":
        cfg = bootstrap()
        print(json.dumps(cfg, indent=2))
        return
    if argv[0] == "subscribe" and len(argv) >= 2:
        org_id = argv[1]
        tier = argv[2] if len(argv) >= 3 else None
        # Boot Flask app context so SQLAlchemy session works.
        from server import app
        with app.app_context():
            result = subscribe_org(org_id, tier)
            print(json.dumps(result, indent=2))
        return
    print("Unknown command. Use `bootstrap` or `subscribe <org_id> [tier]`.")
    sys.exit(1)


if __name__ == "__main__":
    main()
