"""What happens on the booking page before anyone pays.

The six-step booking flow recorded nothing until step 6, and only then if the
visitor typed a valid email. Somebody who gave an address, picked their items,
chose a day, saw a locked price and then closed the tab left no trace at all —
no lead, no number, no row. In the 30 days to 15 Sep the pricing dashboard
read zero quotes in every price band, which was not a demand signal so much as
the absence of a measurement.

One row per booking attempt, keyed on a session id the page generates, updated
as they move through the steps. It is the drop-off report and, once a phone or
email appears, a lead the desk can call.
"""
from datetime import datetime, timezone

from sqlalchemy import Column, String, Text, DateTime, Float, Integer, Boolean, JSON, Index

from models import db, generate_uuid


def _now():
    return datetime.now(timezone.utc).replace(tzinfo=None)


# The steps as the page numbers them. Kept here so the report and the frontend
# cannot drift apart silently.
STEP_LABELS = {
    1: "address",
    2: "photos",
    3: "items",
    4: "schedule",
    5: "estimate",
    6: "payment",
}
LAST_STEP = 6


class BookingFunnel(db.Model):
    __tablename__ = "booking_funnel"

    id = Column(String(36), primary_key=True, default=generate_uuid)
    # Generated by the page, stable for one booking attempt across steps.
    session_id = Column(String(64), nullable=False, unique=True, index=True)

    step = Column(Integer, nullable=False, default=1)          # where they are now
    max_step = Column(Integer, nullable=False, default=1)      # the furthest they got
    # A price they were actually shown. This is the number that makes an
    # abandoned session worth a phone call.
    quoted_price = Column(Float, nullable=True)
    quote_accepted = Column(Boolean, nullable=False, default=False)

    zip_code = Column(String(12), nullable=True, index=True)
    address = Column(Text, nullable=True)
    items = Column(JSON, nullable=True)
    signals = Column(JSON, nullable=True)     # what happened on the address step (see booking_funnel.signal)
    scheduled_for = Column(String(40), nullable=True)

    name = Column(String(160), nullable=True)
    phone = Column(String(40), nullable=True)
    phone_digits = Column(String(10), nullable=True, index=True)
    email = Column(String(254), nullable=True, index=True)

    lead_source = Column(String(100), nullable=True, index=True)
    referrer = Column(String(300), nullable=True)
    user_agent = Column(String(300), nullable=True)

    # It turned into work.
    converted = Column(Boolean, nullable=False, default=False, index=True)
    job_id = Column(String(36), nullable=True, index=True)
    # The desk has already been given this one as a lead.
    surfaced_at = Column(DateTime, nullable=True)

    created_at = Column(DateTime, default=_now, nullable=False, index=True)
    updated_at = Column(DateTime, default=_now, onupdate=_now, nullable=False, index=True)

    __table_args__ = (Index("ix_booking_funnel_open", "converted", "max_step"),)

    @property
    def reachable(self):
        """Can a person actually follow this up?"""
        return bool(self.phone_digits or self.email)

    @property
    def step_label(self):
        return STEP_LABELS.get(self.max_step, str(self.max_step))

    def to_dict(self):
        return {
            "id": self.id, "session_id": self.session_id,
            "step": self.step, "max_step": self.max_step, "reached": self.step_label,
            "quoted_price": self.quoted_price, "quote_accepted": self.quote_accepted,
            "zip": self.zip_code, "address": self.address, "items": self.items or [],
            "scheduled_for": self.scheduled_for,
            "name": self.name, "phone": self.phone, "email": self.email,
            "lead_source": self.lead_source, "reachable": self.reachable,
            "converted": self.converted, "job_id": self.job_id,
            "created_at": self.created_at.isoformat() + "Z" if self.created_at else None,
            "updated_at": self.updated_at.isoformat() + "Z" if self.updated_at else None,
        }
